/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket110.xml
 */
/**
 * Protocol used in Minecraft: Pocket Edition and variants. The network part of the
 * protocol is managed by RakNet.
 * 
 * <h3>Login sequence</h3>
 * + The client sends a Login packet with the details of its game and its account
 * + The server always replies with a PlayerStatus
 * + If status field in the packet sent was different from ok the connection is closed
 */
module sul.protocol.pocket110;

public import sul.protocol.pocket110.types;

public import sul.protocol.pocket110.play;
