/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/biomes.xml
 */
module sul.biomes;

public struct Biome
{

    string name;
    ubyte id;
    float temperature;

}

public enum Biomes : Biome
{

    OCEAN = Biome("ocean", 0, 0.5f),
    PLAINS = Biome("plains", 1, 0.8f),
    DESERT = Biome("desert", 2, 2f),
    EXTREME_HILLS = Biome("extreme hills", 3, 0.2f),
    FOREST = Biome("forest", 4, 0.7f),
    TAIGA = Biome("taiga", 5, 0.05f),
    SWAMPLAND = Biome("swampland", 6, 0.8f),
    RIVER = Biome("river", 7, 0.5f),
    HELL = Biome("hell", 8, 2f),
    THE_END = Biome("the end", 9, 0.5f),
    FROZEN_OCEAN = Biome("frozen ocean", 10, 0f),
    FROZEN_RIVER = Biome("frozen river", 11, 0f),
    ICE_PLAINS = Biome("ice plains", 12, 0f),
    ICE_MOUNTAINS = Biome("ice mountains", 13, 0f),
    MUSHROOM_ISLAND = Biome("mushroom island", 14, 0.9f),
    MUSHROOM_ISLAND_SHORE = Biome("mushroom island shore", 15, 0.9f),
    BEACH = Biome("beach", 16, 0.8f),
    DESERT_HILLS = Biome("desert hills", 17, 2f),
    FOREST_HILLS = Biome("forest hills", 18, 0.7f),
    TAIGA_HILLS = Biome("taiga hills", 19, 0.2f),
    EXTREME_HILLS_EDGE = Biome("extreme hills edge", 20, 0.2f),
    JUNGLE = Biome("jungle", 21, 1.2f),
    JUNGLE_HILLS = Biome("jungle hills", 22, 1.2f),
    JUNGLE_EDGE = Biome("jungle edge", 23, 0.95f),
    DEEP_OCEAN = Biome("deep ocean", 24, 0.5f),
    STONE_BEACH = Biome("stone beach", 25, 0.2f),
    COLD_BEACH = Biome("cold beach", 26, 0.05f),
    BIRCH_FOREST = Biome("birch forest", 27, 0.6f),
    BIRCH_FOREST_HILLS = Biome("birch forest hills", 28, 0.6f),
    ROOFED_FOREST = Biome("roofed forest", 29, 0.7f),
    COLD_TAIGA = Biome("cold taiga", 30, -0.5f),
    COLD_TAIGA_HILLS = Biome("cold taiga hills", 31, -0.5f),
    MEGA_TAIGA = Biome("mega taiga", 32, 0.3f),
    MEGA_TAIGA_HILLS = Biome("mega taiga hills", 33, 0.3f),
    EXTREME_HILLS_PLUS = Biome("extreme hills plus", 34, 0.2f),
    SAVANNA = Biome("savanna", 35, 1.2f),
    SAVANNA_PLATEAU = Biome("savanna plateau", 36, 1f),
    MESA = Biome("mesa", 37, 2f),
    MESA_PLATEAU_F = Biome("mesa plateau f", 38, 2f),
    MESA_PLATEAU = Biome("mesa plateau", 39, 2f),
    THE_VOID = Biome("the void", 127, 0f),
    PLAINS_M = Biome("plains m", 128, 0.5f),
    SUNFLOWER_PLAINS = Biome("sunflower plains", 129, 0.8f),
    DESERT_M = Biome("desert m", 130, 2f),
    EXTREME_HILLS_M = Biome("extreme hills m", 131, 0.2f),
    FLOWER_FOREST = Biome("flower forest", 132, 0.7f),
    TAIGA_M = Biome("taiga m", 133, 0.05f),
    SWAMPLAND_M = Biome("swampland m", 134, 0.8f),
    ICE_PLAINS_SPIKES = Biome("ice plains spikes", 140, 0f),
    JUNGLE_M = Biome("jungle m", 149, 1.2f),
    JUNGLE_EDGE_M = Biome("jungle edge m", 151, 0.95f),
    BIRCH_FOREST_M = Biome("birch forest m", 155, 0.6f),
    BIRCH_FOREST_HILLS_M = Biome("birch forest hills m", 156, 0.6f),
    ROOFED_FOREST_M = Biome("roofed forest m", 157, 0.7f),
    COLD_TAIGA_M = Biome("cold taiga m", 158, -0.5f),
    MEGA_SPRUCE_TAIGA = Biome("mega spruce taiga", 160, 0.3f),
    REDWOOD_TAIGA_HILLS_M = Biome("redwood taiga hills m", 161, 0.3f),
    EXTREME_HILLS_PLUS_M = Biome("extreme hills plus m", 162, 0.2f),
    SAVANNA_M = Biome("savanna m", 163, 1.2f),
    SAVANNA_PLATEAU_M = Biome("savanna plateau m", 164, 1f),
    MESA_BRYCE = Biome("mesa bryce", 165, 2f),
    MESA_PLATEAU_F_M = Biome("mesa plateau f m", 166, 2f),
    MESA_PLATEAU_M = Biome("mesa plateau m", 167, 2f),

}
