/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/biomes.xml
 */
module sul.biomes;

public struct Biome
{

    string name;
    ubyte id;
    float temperature;

}

public enum Biomes : Biome
{

    ocean = Biome("ocean", 0, 0.5f),
    plains = Biome("plains", 1, 0.8f),
    desert = Biome("desert", 2, 2f),
    extremeHills = Biome("extreme hills", 3, 0.2f),
    forest = Biome("forest", 4, 0.7f),
    taiga = Biome("taiga", 5, 0.05f),
    swampland = Biome("swampland", 6, 0.8f),
    river = Biome("river", 7, 0.5f),
    hell = Biome("hell", 8, 2f),
    theEnd = Biome("the end", 9, 0.5f),
    frozenOcean = Biome("frozen ocean", 10, 0f),
    frozenRiver = Biome("frozen river", 11, 0f),
    icePlains = Biome("ice plains", 12, 0f),
    iceMountains = Biome("ice mountains", 13, 0f),
    mushroomIsland = Biome("mushroom island", 14, 0.9f),
    mushroomIslandShore = Biome("mushroom island shore", 15, 0.9f),
    beach = Biome("beach", 16, 0.8f),
    desertHills = Biome("desert hills", 17, 2f),
    forestHills = Biome("forest hills", 18, 0.7f),
    taigaHills = Biome("taiga hills", 19, 0.2f),
    extremeHillsEdge = Biome("extreme hills edge", 20, 0.2f),
    jungle = Biome("jungle", 21, 1.2f),
    jungleHills = Biome("jungle hills", 22, 1.2f),
    jungleEdge = Biome("jungle edge", 23, 0.95f),
    deepOcean = Biome("deep ocean", 24, 0.5f),
    stoneBeach = Biome("stone beach", 25, 0.2f),
    coldBeach = Biome("cold beach", 26, 0.05f),
    birchForest = Biome("birch forest", 27, 0.6f),
    birchForestHills = Biome("birch forest hills", 28, 0.6f),
    roofedForest = Biome("roofed forest", 29, 0.7f),
    coldTaiga = Biome("cold taiga", 30, -0.5f),
    coldTaigaHills = Biome("cold taiga hills", 31, -0.5f),
    megaTaiga = Biome("mega taiga", 32, 0.3f),
    megaTaigaHills = Biome("mega taiga hills", 33, 0.3f),
    extremeHillsPlus = Biome("extreme hills plus", 34, 0.2f),
    savanna = Biome("savanna", 35, 1.2f),
    savannaPlateau = Biome("savanna plateau", 36, 1f),
    mesa = Biome("mesa", 37, 2f),
    mesaPlateauF = Biome("mesa plateau f", 38, 2f),
    mesaPlateau = Biome("mesa plateau", 39, 2f),
    theVoid = Biome("the void", 127, 0f),
    plainsM = Biome("plains m", 128, 0.5f),
    sunflowerPlains = Biome("sunflower plains", 129, 0.8f),
    desertM = Biome("desert m", 130, 2f),
    extremeHillsM = Biome("extreme hills m", 131, 0.2f),
    flowerForest = Biome("flower forest", 132, 0.7f),
    taigaM = Biome("taiga m", 133, 0.05f),
    swamplandM = Biome("swampland m", 134, 0.8f),
    icePlainsSpikes = Biome("ice plains spikes", 140, 0f),
    jungleM = Biome("jungle m", 149, 1.2f),
    jungleEdgeM = Biome("jungle edge m", 151, 0.95f),
    birchForestM = Biome("birch forest m", 155, 0.6f),
    birchForestHillsM = Biome("birch forest hills m", 156, 0.6f),
    roofedForestM = Biome("roofed forest m", 157, 0.7f),
    coldTaigaM = Biome("cold taiga m", 158, -0.5f),
    megaSpruceTaiga = Biome("mega spruce taiga", 160, 0.3f),
    redwoodTaigaHillsM = Biome("redwood taiga hills m", 161, 0.3f),
    extremeHillsPlusM = Biome("extreme hills plus m", 162, 0.2f),
    savannaM = Biome("savanna m", 163, 1.2f),
    savannaPlateauM = Biome("savanna plateau m", 164, 1f),
    mesaBryce = Biome("mesa bryce", 165, 2f),
    mesaPlateauFM = Biome("mesa plateau f m", 166, 2f),
    mesaPlateauM = Biome("mesa plateau m", 167, 2f),

}
