/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/effects.xml
 */
module sul.effects;

public struct EffectValue
{

    bool exists;
    ubyte id;

    alias exists this;

}

public struct Effect
{

    string name;
    EffectValue minecraft, pocket;
    uint particles;

}

public enum Effects : Effect
{

    speed = Effect("speed", EffectValue(true, 1), EffectValue(true, 1), 8171462),
    slowness = Effect("slowness", EffectValue(true, 2), EffectValue(true, 2), 5926017),
    haste = Effect("haste", EffectValue(true, 3), EffectValue(true, 3), 14270531),
    miningFatigue = Effect("mining_fatigue", EffectValue(true, 4), EffectValue(true, 4), 4866583),
    strength = Effect("strength", EffectValue(true, 5), EffectValue(true, 5), 9643043),
    instantHealth = Effect("instant_health", EffectValue(true, 6), EffectValue(true, 6), 16262179),
    instantDamage = Effect("instant_damage", EffectValue(true, 7), EffectValue(true, 7), 4393481),
    jumpBoost = Effect("jump_boost", EffectValue(true, 8), EffectValue(true, 8), 7889559),
    nausea = Effect("nausea", EffectValue(true, 9), EffectValue(true, 9), 5578058),
    regeneration = Effect("regeneration", EffectValue(true, 10), EffectValue(true, 10), 13458603),
    resistance = Effect("resistance", EffectValue(true, 11), EffectValue(true, 11), 10044730),
    fireResistance = Effect("fire_resistance", EffectValue(true, 12), EffectValue(true, 12), 14981690),
    waterBreathing = Effect("water_breathing", EffectValue(true, 13), EffectValue(true, 13), 3035801),
    invisibility = Effect("invisibility", EffectValue(true, 14), EffectValue(true, 14), 8356754),
    blindness = Effect("blindness", EffectValue(true, 15), EffectValue(true, 15), 2039587),
    nightVision = Effect("night_vision", EffectValue(true, 16), EffectValue(true, 16), 2039713),
    hunger = Effect("hunger", EffectValue(true, 17), EffectValue(true, 17), 5797459),
    weakness = Effect("weakness", EffectValue(true, 18), EffectValue(true, 18), 4738376),
    poison = Effect("poison", EffectValue(true, 19), EffectValue(true, 19), 5149489),
    wither = Effect("wither", EffectValue(true, 20), EffectValue(true, 20), 3484199),
    healthBoost = Effect("health_boost", EffectValue(true, 21), EffectValue(true, 21), 16284963),
    absorption = Effect("absorption", EffectValue(true, 22), EffectValue(true, 22), 2445989),
    saturation = Effect("saturation", EffectValue(true, 23), EffectValue(true, 23), 16262179),
    glowing = Effect("glowing", EffectValue(true, 24), EffectValue(false), 9740385),
    levitation = Effect("levitation", EffectValue(true, 25), EffectValue(true, 24), 13565951),
    luck = Effect("luck", EffectValue(true, 26), EffectValue(false), 3381504),
    badLuck = Effect("bad_luck", EffectValue(true, 27), EffectValue(false), 12624973),

}
