/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/java315.xml
 */
module sul.protocol.java315;

public import sul.protocol.java315.types;

public import sul.protocol.java315.status;
public import sul.protocol.java315.login;
public import sul.protocol.java315.clientbound;
public import sul.protocol.java315.serverbound;
