/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/metadata/bedrock160.xml
 */
module sul.metadata.bedrock160;

import std.typecons : Tuple, tuple;

import sul.utils.buffer : Buffer;
import sul.utils.metadataflags;
import sul.utils.var;

static import sul.protocol.bedrock160.types;

alias Changed(T) = Tuple!(T, "value", bool, "changed");

enum MetadataType : uint {

	BYTE = 0,
	SHORT = 1,
	INT = 2,
	FLOAT = 3,
	STRING = 4,
	SLOT = 5,
	BLOCK_POSITION = 6,
	LONG = 7,
	ENTITY_POSITION = 8,
}

class Metadata {

	public enum ENTITY_FLAGS : size_t {
		ON_FIRE = 0,
		SNEAKING = 1,
		RIDING = 2,
		SPRINTING = 3,
		USING_ITEM = 4,
		INVISIBLE = 5,
		TEMPTED = 6,
		IN_LOVE = 7,
		SADDLED = 8,
		POWERED = 9,
		IGNITED = 10,
		BABY = 11,
		CONVERTING = 12,
		CRITICAL = 13,
		SHOW_NAMETAG = 14,
		ALWAYS_SHOW_NAMETAG = 15,
		NO_AI = 16,
		SILENT = 17,
		CLIMBING = 18,
		CAN_CLIMB = 19,
		CAN_SWIM = 20,
		CAN_FLY = 21,
		RESTING = 22,
		SITTING = 23,
		ANGRY = 24,
		INTERESTED = 25,
		CHARGED = 26,
		TAMED = 27,
		LEASHED = 28,
		SHEARED = 29,
		GLIDING = 30,
		ELDER = 31,
		MOVING = 32,
		BREATHING = 33,
		CHESTED = 34,
		STACKABLE = 35,
		SHOWBASE = 36,
		REARING = 37,
		VIBRATING = 38,
		IDLING = 39,
		EVOKER_SPELL = 40,
		CHARGE_ATTACK = 41,
		IS_WASD_CONTROLLED = 42,
		LINGER = 44,
		COLLIDE = 45,
		GRAVITY = 46,
		DANCING = 48,
	}
	public enum uint HEALTH = 1;
	public enum uint VARIANT = 2;
	public enum uint COLOR = 3;
	public enum uint NAMETAG = 4;
	public enum uint OWNER = 5;
	public enum uint TARGET = 6;
	public enum uint AIR = 7;
	public enum uint POTION_COLOR = 8;
	public enum uint POTION_AMBIENT = 9;
	public enum uint HURT_TIME = 11;
	public enum uint HURT_DIRECTION = 12;
	public enum uint PADDLE_TIME_LEFT = 13;
	public enum uint PADDLE_TIME_RIGHT = 14;
	public enum uint EXPERIENCE_COUNT = 15;
	public enum uint MINECART_BLOCK = 16;
	public enum uint MINECART_OFFSET = 17;
	public enum uint MINECART_HAS_BLOCK = 18;
	public enum uint ENDERMAN_ITEM_ID = 23;
	public enum uint ENDERMAN_ITEM_DAMAGE = 24;
	public enum uint AGE = 25;
	public enum PLAYER_FLAGS : size_t {
		ASLEEP = 1,
	}
	public enum uint PLAYER_INDEX = 28;
	public enum uint BED_POSITION = 29;
	public enum uint FIREBALL_POWER_X = 30;
	public enum uint FIREBALL_POWER_Y = 31;
	public enum uint FIREBALL_POWER_Z = 32;
	public enum uint POTION_AUX_VALUE = 37;
	public enum uint LEAD_HOLDER = 38;
	public enum uint SCALE = 39;
	public enum uint INTERACTIVE_TAG = 40;
	public enum uint NPC_ID = 41;
	public enum uint INTERACTIVE_TAG_URL = 42;
	public enum uint MAX_AIR = 43;
	public enum uint MARK_VARIANT = 44;
	public enum uint BLOCK_TARGET = 48;
	public enum uint INVULNERABLE_TIME = 49;
	public enum uint CENTER_HEAD_TARGET = 50;
	public enum uint LEFT_HEAD_TARGET = 51;
	public enum uint RIGHT_HEAD_TARGET = 52;
	public enum uint BOUNDING_BOX_WIDTH = 54;
	public enum uint BOUNDING_BOX_HEIGHT = 55;
	public enum uint FUSE_LENGTH = 56;
	public enum uint RIDER_SEAT_POSITION = 57;
	public enum uint RIDER_ROTATION_LOCKED = 58;
	public enum uint RIDER_MAX_ROTATION = 59;
	public enum uint RIDER_MIN_ROTATION = 60;
	public enum uint AREA_EFFECT_CLOUD_RADIUS = 61;
	public enum uint AREA_EFFECT_CLOUD_WAITING = 62;
	public enum uint AREA_EFFECT_CLOUD_PARTICLE = 63;
	public enum uint SHULKER_PEAK_HEIGHT = 64;
	public enum uint SHULKER_DIRECTION = 65;
	public enum uint SHULKER_ATTACHMENT = 67;
	public enum uint TRADING_PLAYER = 68;
	public enum uint COMMAND_BLOCK_COMMAND = 71;
	public enum uint COMMAND_BLOCK_LAST_OUTPUT = 72;
	public enum uint COMMAND_BLOCK_TRACK_OUTPUT = 73;
	public enum uint CONTROLLING_RIDER_SEAT_NUMBER = 74;
	public enum uint STRENGTH = 75;
	public enum uint MAX_STRENGTH = 76;

	public DecodedMetadata[] decoded;

	private bool _cached = false;
	private ubyte[] _cache;

	private void delegate(Buffer) pure nothrow @safe[] _changed;

	private MetadataFlags!(long) _entityFlags = cast(MetadataFlags!(long))0;
	private Changed!(int) _health;
	private Changed!(int) _variant;
	private Changed!(byte) _color;
	private Changed!(string) _nametag;
	private Changed!(long) _owner = tuple(cast(long)-1, false);
	private Changed!(long) _target;
	private short _air = cast(short)0;
	private Changed!(int) _potionColor;
	private Changed!(byte) _potionAmbient;
	private Changed!(int) _hurtTime;
	private Changed!(int) _hurtDirection;
	private Changed!(float) _paddleTimeLeft;
	private Changed!(float) _paddleTimeRight;
	private Changed!(int) _experienceCount;
	private Changed!(int) _minecartBlock;
	private Changed!(int) _minecartOffset;
	private Changed!(byte) _minecartHasBlock;
	private Changed!(short) _endermanItemId;
	private Changed!(short) _endermanItemDamage;
	private Changed!(short) _age;
	private Changed!(MetadataFlags!(byte)) _playerFlags;
	private Changed!(int) _playerIndex;
	private Changed!(Tuple!(int, "x", int, "y", int, "z")) _bedPosition;
	private Changed!(float) _fireballPowerX;
	private Changed!(float) _fireballPowerY;
	private Changed!(float) _fireballPowerZ;
	private Changed!(short) _potionAuxValue;
	private long _leadHolder = cast(long)-1;
	private Changed!(float) _scale = tuple(cast(float)1, false);
	private Changed!(string) _interactiveTag;
	private Changed!(string) _npcId;
	private Changed!(string) _interactiveTagUrl;
	private Changed!(short) _maxAir;
	private Changed!(int) _markVariant;
	private Changed!(Tuple!(int, "x", int, "y", int, "z")) _blockTarget;
	private Changed!(int) _invulnerableTime;
	private Changed!(long) _centerHeadTarget;
	private Changed!(long) _leftHeadTarget;
	private Changed!(long) _rightHeadTarget;
	private Changed!(float) _boundingBoxWidth;
	private Changed!(float) _boundingBoxHeight;
	private Changed!(int) _fuseLength;
	private Changed!(Tuple!(float, "x", float, "y", float, "z")) _riderSeatPosition;
	private Changed!(byte) _riderRotationLocked;
	private Changed!(float) _riderMaxRotation;
	private Changed!(float) _riderMinRotation;
	private Changed!(float) _areaEffectCloudRadius = tuple(cast(float)0.5, false);
	private Changed!(int) _areaEffectCloudWaiting;
	private Changed!(int) _areaEffectCloudParticle;
	private Changed!(int) _shulkerPeakHeight;
	private Changed!(byte) _shulkerDirection;
	private Changed!(Tuple!(int, "x", int, "y", int, "z")) _shulkerAttachment;
	private Changed!(long) _tradingPlayer;
	private Changed!(string) _commandBlockCommand;
	private Changed!(string) _commandBlockLastOutput;
	private Changed!(string) _commandBlockTrackOutput;
	private Changed!(byte) _controllingRiderSeatNumber;
	private Changed!(int) _strength;
	private Changed!(int) _maxStrength;

	public pure nothrow @safe this() {
		this.reset();
	}

	public pure nothrow @safe void reset() {
		this._changed = [
			&this.encodeEntityFlags,
			&this.encodeAir,
			&this.encodeLeadHolder,
		];
	}

	public pure nothrow @property @safe @nogc long entityFlags() {
		return _entityFlags;
	}

	public pure nothrow @property @safe long entityFlags(long value) {
		this._cached = false;
		this._entityFlags = value;
		return value;
	}

	public pure nothrow @safe encodeEntityFlags(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(0));
			writeBytes(varuint.encode(7));
			writeBytes(varlong.encode(this._entityFlags));
		}
	}

	public pure nothrow @property @safe bool onFire() {
		return _entityFlags._0;
	}

	public pure nothrow @property @safe bool onFire(bool value) {
		_entityFlags._0 = value;
		return value;
	}

	public pure nothrow @property @safe bool sneaking() {
		return _entityFlags._1;
	}

	public pure nothrow @property @safe bool sneaking(bool value) {
		_entityFlags._1 = value;
		return value;
	}

	public pure nothrow @property @safe bool riding() {
		return _entityFlags._2;
	}

	public pure nothrow @property @safe bool riding(bool value) {
		_entityFlags._2 = value;
		return value;
	}

	public pure nothrow @property @safe bool sprinting() {
		return _entityFlags._3;
	}

	public pure nothrow @property @safe bool sprinting(bool value) {
		_entityFlags._3 = value;
		return value;
	}

	public pure nothrow @property @safe bool usingItem() {
		return _entityFlags._4;
	}

	public pure nothrow @property @safe bool usingItem(bool value) {
		_entityFlags._4 = value;
		return value;
	}

	public pure nothrow @property @safe bool invisible() {
		return _entityFlags._5;
	}

	public pure nothrow @property @safe bool invisible(bool value) {
		_entityFlags._5 = value;
		return value;
	}

	public pure nothrow @property @safe bool tempted() {
		return _entityFlags._6;
	}

	public pure nothrow @property @safe bool tempted(bool value) {
		_entityFlags._6 = value;
		return value;
	}

	public pure nothrow @property @safe bool inLove() {
		return _entityFlags._7;
	}

	public pure nothrow @property @safe bool inLove(bool value) {
		_entityFlags._7 = value;
		return value;
	}

	public pure nothrow @property @safe bool saddled() {
		return _entityFlags._8;
	}

	public pure nothrow @property @safe bool saddled(bool value) {
		_entityFlags._8 = value;
		return value;
	}

	public pure nothrow @property @safe bool powered() {
		return _entityFlags._9;
	}

	public pure nothrow @property @safe bool powered(bool value) {
		_entityFlags._9 = value;
		return value;
	}

	public pure nothrow @property @safe bool ignited() {
		return _entityFlags._10;
	}

	public pure nothrow @property @safe bool ignited(bool value) {
		_entityFlags._10 = value;
		return value;
	}

	public pure nothrow @property @safe bool baby() {
		return _entityFlags._11;
	}

	public pure nothrow @property @safe bool baby(bool value) {
		_entityFlags._11 = value;
		return value;
	}

	public pure nothrow @property @safe bool converting() {
		return _entityFlags._12;
	}

	public pure nothrow @property @safe bool converting(bool value) {
		_entityFlags._12 = value;
		return value;
	}

	public pure nothrow @property @safe bool critical() {
		return _entityFlags._13;
	}

	public pure nothrow @property @safe bool critical(bool value) {
		_entityFlags._13 = value;
		return value;
	}

	public pure nothrow @property @safe bool showNametag() {
		return _entityFlags._14;
	}

	public pure nothrow @property @safe bool showNametag(bool value) {
		_entityFlags._14 = value;
		return value;
	}

	public pure nothrow @property @safe bool alwaysShowNametag() {
		return _entityFlags._15;
	}

	public pure nothrow @property @safe bool alwaysShowNametag(bool value) {
		_entityFlags._15 = value;
		return value;
	}

	public pure nothrow @property @safe bool noAi() {
		return _entityFlags._16;
	}

	public pure nothrow @property @safe bool noAi(bool value) {
		_entityFlags._16 = value;
		return value;
	}

	public pure nothrow @property @safe bool silent() {
		return _entityFlags._17;
	}

	public pure nothrow @property @safe bool silent(bool value) {
		_entityFlags._17 = value;
		return value;
	}

	public pure nothrow @property @safe bool climbing() {
		return _entityFlags._18;
	}

	public pure nothrow @property @safe bool climbing(bool value) {
		_entityFlags._18 = value;
		return value;
	}

	public pure nothrow @property @safe bool canClimb() {
		return _entityFlags._19;
	}

	public pure nothrow @property @safe bool canClimb(bool value) {
		_entityFlags._19 = value;
		return value;
	}

	public pure nothrow @property @safe bool canSwim() {
		return _entityFlags._20;
	}

	public pure nothrow @property @safe bool canSwim(bool value) {
		_entityFlags._20 = value;
		return value;
	}

	public pure nothrow @property @safe bool canFly() {
		return _entityFlags._21;
	}

	public pure nothrow @property @safe bool canFly(bool value) {
		_entityFlags._21 = value;
		return value;
	}

	public pure nothrow @property @safe bool resting() {
		return _entityFlags._22;
	}

	public pure nothrow @property @safe bool resting(bool value) {
		_entityFlags._22 = value;
		return value;
	}

	public pure nothrow @property @safe bool sitting() {
		return _entityFlags._23;
	}

	public pure nothrow @property @safe bool sitting(bool value) {
		_entityFlags._23 = value;
		return value;
	}

	public pure nothrow @property @safe bool angry() {
		return _entityFlags._24;
	}

	public pure nothrow @property @safe bool angry(bool value) {
		_entityFlags._24 = value;
		return value;
	}

	public pure nothrow @property @safe bool interested() {
		return _entityFlags._25;
	}

	public pure nothrow @property @safe bool interested(bool value) {
		_entityFlags._25 = value;
		return value;
	}

	public pure nothrow @property @safe bool charged() {
		return _entityFlags._26;
	}

	public pure nothrow @property @safe bool charged(bool value) {
		_entityFlags._26 = value;
		return value;
	}

	public pure nothrow @property @safe bool tamed() {
		return _entityFlags._27;
	}

	public pure nothrow @property @safe bool tamed(bool value) {
		_entityFlags._27 = value;
		return value;
	}

	public pure nothrow @property @safe bool leashed() {
		return _entityFlags._28;
	}

	public pure nothrow @property @safe bool leashed(bool value) {
		_entityFlags._28 = value;
		return value;
	}

	public pure nothrow @property @safe bool sheared() {
		return _entityFlags._29;
	}

	public pure nothrow @property @safe bool sheared(bool value) {
		_entityFlags._29 = value;
		return value;
	}

	public pure nothrow @property @safe bool gliding() {
		return _entityFlags._30;
	}

	public pure nothrow @property @safe bool gliding(bool value) {
		_entityFlags._30 = value;
		return value;
	}

	public pure nothrow @property @safe bool elder() {
		return _entityFlags._31;
	}

	public pure nothrow @property @safe bool elder(bool value) {
		_entityFlags._31 = value;
		return value;
	}

	public pure nothrow @property @safe bool moving() {
		return _entityFlags._32;
	}

	public pure nothrow @property @safe bool moving(bool value) {
		_entityFlags._32 = value;
		return value;
	}

	public pure nothrow @property @safe bool breathing() {
		return _entityFlags._33;
	}

	public pure nothrow @property @safe bool breathing(bool value) {
		_entityFlags._33 = value;
		return value;
	}

	public pure nothrow @property @safe bool chested() {
		return _entityFlags._34;
	}

	public pure nothrow @property @safe bool chested(bool value) {
		_entityFlags._34 = value;
		return value;
	}

	public pure nothrow @property @safe bool stackable() {
		return _entityFlags._35;
	}

	public pure nothrow @property @safe bool stackable(bool value) {
		_entityFlags._35 = value;
		return value;
	}

	public pure nothrow @property @safe bool showbase() {
		return _entityFlags._36;
	}

	public pure nothrow @property @safe bool showbase(bool value) {
		_entityFlags._36 = value;
		return value;
	}

	public pure nothrow @property @safe bool rearing() {
		return _entityFlags._37;
	}

	public pure nothrow @property @safe bool rearing(bool value) {
		_entityFlags._37 = value;
		return value;
	}

	public pure nothrow @property @safe bool vibrating() {
		return _entityFlags._38;
	}

	public pure nothrow @property @safe bool vibrating(bool value) {
		_entityFlags._38 = value;
		return value;
	}

	public pure nothrow @property @safe bool idling() {
		return _entityFlags._39;
	}

	public pure nothrow @property @safe bool idling(bool value) {
		_entityFlags._39 = value;
		return value;
	}

	public pure nothrow @property @safe bool evokerSpell() {
		return _entityFlags._40;
	}

	public pure nothrow @property @safe bool evokerSpell(bool value) {
		_entityFlags._40 = value;
		return value;
	}

	public pure nothrow @property @safe bool chargeAttack() {
		return _entityFlags._41;
	}

	public pure nothrow @property @safe bool chargeAttack(bool value) {
		_entityFlags._41 = value;
		return value;
	}

	public pure nothrow @property @safe bool isWasdControlled() {
		return _entityFlags._42;
	}

	public pure nothrow @property @safe bool isWasdControlled(bool value) {
		_entityFlags._42 = value;
		return value;
	}

	public pure nothrow @property @safe bool linger() {
		return _entityFlags._44;
	}

	public pure nothrow @property @safe bool linger(bool value) {
		_entityFlags._44 = value;
		return value;
	}

	public pure nothrow @property @safe bool collide() {
		return _entityFlags._45;
	}

	public pure nothrow @property @safe bool collide(bool value) {
		_entityFlags._45 = value;
		return value;
	}

	public pure nothrow @property @safe bool gravity() {
		return _entityFlags._46;
	}

	public pure nothrow @property @safe bool gravity(bool value) {
		_entityFlags._46 = value;
		return value;
	}

	public pure nothrow @property @safe bool dancing() {
		return _entityFlags._48;
	}

	public pure nothrow @property @safe bool dancing(bool value) {
		_entityFlags._48 = value;
		return value;
	}

	public pure nothrow @property @safe @nogc int health() {
		return _health.value;
	}

	public pure nothrow @property @safe int health(int value) {
		this._cached = false;
		this._health.value = value;
		if(!this._health.changed) {
			this._health.changed = true;
			this._changed ~= &this.encodeHealth;
		}
		return value;
	}

	public pure nothrow @safe encodeHealth(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(1));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._health.value));
		}
	}

	public pure nothrow @property @safe @nogc int variant() {
		return _variant.value;
	}

	public pure nothrow @property @safe int variant(int value) {
		this._cached = false;
		this._variant.value = value;
		if(!this._variant.changed) {
			this._variant.changed = true;
			this._changed ~= &this.encodeVariant;
		}
		return value;
	}

	public pure nothrow @safe encodeVariant(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(2));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._variant.value));
		}
	}

	public pure nothrow @property @safe @nogc byte color() {
		return _color.value;
	}

	public pure nothrow @property @safe byte color(byte value) {
		this._cached = false;
		this._color.value = value;
		if(!this._color.changed) {
			this._color.changed = true;
			this._changed ~= &this.encodeColor;
		}
		return value;
	}

	public pure nothrow @safe encodeColor(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(3));
			writeBytes(varuint.encode(0));
			writeLittleEndianByte(this._color.value);
		}
	}

	public pure nothrow @property @safe @nogc string nametag() {
		return _nametag.value;
	}

	public pure nothrow @property @safe string nametag(string value) {
		this._cached = false;
		this._nametag.value = value;
		if(!this._nametag.changed) {
			this._nametag.changed = true;
			this._changed ~= &this.encodeNametag;
		}
		return value;
	}

	public pure nothrow @safe encodeNametag(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(4));
			writeBytes(varuint.encode(4));
			writeBytes(varuint.encode(cast(uint)this._nametag.value.length)); writeString(this._nametag.value);
		}
	}

	public pure nothrow @property @safe @nogc long owner() {
		return _owner.value;
	}

	public pure nothrow @property @safe long owner(long value) {
		this._cached = false;
		this._owner.value = value;
		if(!this._owner.changed) {
			this._owner.changed = true;
			this._changed ~= &this.encodeOwner;
		}
		return value;
	}

	public pure nothrow @safe encodeOwner(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(5));
			writeBytes(varuint.encode(7));
			writeBytes(varlong.encode(this._owner.value));
		}
	}

	public pure nothrow @property @safe @nogc long target() {
		return _target.value;
	}

	public pure nothrow @property @safe long target(long value) {
		this._cached = false;
		this._target.value = value;
		if(!this._target.changed) {
			this._target.changed = true;
			this._changed ~= &this.encodeTarget;
		}
		return value;
	}

	public pure nothrow @safe encodeTarget(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(6));
			writeBytes(varuint.encode(7));
			writeBytes(varlong.encode(this._target.value));
		}
	}

	public pure nothrow @property @safe @nogc short air() {
		return _air;
	}

	public pure nothrow @property @safe short air(short value) {
		this._cached = false;
		this._air = value;
		return value;
	}

	public pure nothrow @safe encodeAir(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(7));
			writeBytes(varuint.encode(1));
			writeLittleEndianShort(this._air);
		}
	}

	public pure nothrow @property @safe @nogc int potionColor() {
		return _potionColor.value;
	}

	public pure nothrow @property @safe int potionColor(int value) {
		this._cached = false;
		this._potionColor.value = value;
		if(!this._potionColor.changed) {
			this._potionColor.changed = true;
			this._changed ~= &this.encodePotionColor;
		}
		return value;
	}

	public pure nothrow @safe encodePotionColor(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(8));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._potionColor.value));
		}
	}

	public pure nothrow @property @safe @nogc byte potionAmbient() {
		return _potionAmbient.value;
	}

	public pure nothrow @property @safe byte potionAmbient(byte value) {
		this._cached = false;
		this._potionAmbient.value = value;
		if(!this._potionAmbient.changed) {
			this._potionAmbient.changed = true;
			this._changed ~= &this.encodePotionAmbient;
		}
		return value;
	}

	public pure nothrow @safe encodePotionAmbient(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(9));
			writeBytes(varuint.encode(0));
			writeLittleEndianByte(this._potionAmbient.value);
		}
	}

	public pure nothrow @property @safe @nogc int hurtTime() {
		return _hurtTime.value;
	}

	public pure nothrow @property @safe int hurtTime(int value) {
		this._cached = false;
		this._hurtTime.value = value;
		if(!this._hurtTime.changed) {
			this._hurtTime.changed = true;
			this._changed ~= &this.encodeHurtTime;
		}
		return value;
	}

	public pure nothrow @safe encodeHurtTime(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(11));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._hurtTime.value));
		}
	}

	public pure nothrow @property @safe @nogc int hurtDirection() {
		return _hurtDirection.value;
	}

	public pure nothrow @property @safe int hurtDirection(int value) {
		this._cached = false;
		this._hurtDirection.value = value;
		if(!this._hurtDirection.changed) {
			this._hurtDirection.changed = true;
			this._changed ~= &this.encodeHurtDirection;
		}
		return value;
	}

	public pure nothrow @safe encodeHurtDirection(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(12));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._hurtDirection.value));
		}
	}

	public pure nothrow @property @safe @nogc float paddleTimeLeft() {
		return _paddleTimeLeft.value;
	}

	public pure nothrow @property @safe float paddleTimeLeft(float value) {
		this._cached = false;
		this._paddleTimeLeft.value = value;
		if(!this._paddleTimeLeft.changed) {
			this._paddleTimeLeft.changed = true;
			this._changed ~= &this.encodePaddleTimeLeft;
		}
		return value;
	}

	public pure nothrow @safe encodePaddleTimeLeft(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(13));
			writeBytes(varuint.encode(3));
			writeLittleEndianFloat(this._paddleTimeLeft.value);
		}
	}

	public pure nothrow @property @safe @nogc float paddleTimeRight() {
		return _paddleTimeRight.value;
	}

	public pure nothrow @property @safe float paddleTimeRight(float value) {
		this._cached = false;
		this._paddleTimeRight.value = value;
		if(!this._paddleTimeRight.changed) {
			this._paddleTimeRight.changed = true;
			this._changed ~= &this.encodePaddleTimeRight;
		}
		return value;
	}

	public pure nothrow @safe encodePaddleTimeRight(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(14));
			writeBytes(varuint.encode(3));
			writeLittleEndianFloat(this._paddleTimeRight.value);
		}
	}

	public pure nothrow @property @safe @nogc int experienceCount() {
		return _experienceCount.value;
	}

	public pure nothrow @property @safe int experienceCount(int value) {
		this._cached = false;
		this._experienceCount.value = value;
		if(!this._experienceCount.changed) {
			this._experienceCount.changed = true;
			this._changed ~= &this.encodeExperienceCount;
		}
		return value;
	}

	public pure nothrow @safe encodeExperienceCount(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(15));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._experienceCount.value));
		}
	}

	public pure nothrow @property @safe @nogc int minecartBlock() {
		return _minecartBlock.value;
	}

	public pure nothrow @property @safe int minecartBlock(int value) {
		this._cached = false;
		this._minecartBlock.value = value;
		if(!this._minecartBlock.changed) {
			this._minecartBlock.changed = true;
			this._changed ~= &this.encodeMinecartBlock;
		}
		return value;
	}

	public pure nothrow @safe encodeMinecartBlock(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(16));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._minecartBlock.value));
		}
	}

	public pure nothrow @property @safe @nogc int minecartOffset() {
		return _minecartOffset.value;
	}

	public pure nothrow @property @safe int minecartOffset(int value) {
		this._cached = false;
		this._minecartOffset.value = value;
		if(!this._minecartOffset.changed) {
			this._minecartOffset.changed = true;
			this._changed ~= &this.encodeMinecartOffset;
		}
		return value;
	}

	public pure nothrow @safe encodeMinecartOffset(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(17));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._minecartOffset.value));
		}
	}

	public pure nothrow @property @safe @nogc byte minecartHasBlock() {
		return _minecartHasBlock.value;
	}

	public pure nothrow @property @safe byte minecartHasBlock(byte value) {
		this._cached = false;
		this._minecartHasBlock.value = value;
		if(!this._minecartHasBlock.changed) {
			this._minecartHasBlock.changed = true;
			this._changed ~= &this.encodeMinecartHasBlock;
		}
		return value;
	}

	public pure nothrow @safe encodeMinecartHasBlock(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(18));
			writeBytes(varuint.encode(0));
			writeLittleEndianByte(this._minecartHasBlock.value);
		}
	}

	public pure nothrow @property @safe @nogc short endermanItemId() {
		return _endermanItemId.value;
	}

	public pure nothrow @property @safe short endermanItemId(short value) {
		this._cached = false;
		this._endermanItemId.value = value;
		if(!this._endermanItemId.changed) {
			this._endermanItemId.changed = true;
			this._changed ~= &this.encodeEndermanItemId;
		}
		return value;
	}

	public pure nothrow @safe encodeEndermanItemId(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(23));
			writeBytes(varuint.encode(1));
			writeLittleEndianShort(this._endermanItemId.value);
		}
	}

	public pure nothrow @property @safe @nogc short endermanItemDamage() {
		return _endermanItemDamage.value;
	}

	public pure nothrow @property @safe short endermanItemDamage(short value) {
		this._cached = false;
		this._endermanItemDamage.value = value;
		if(!this._endermanItemDamage.changed) {
			this._endermanItemDamage.changed = true;
			this._changed ~= &this.encodeEndermanItemDamage;
		}
		return value;
	}

	public pure nothrow @safe encodeEndermanItemDamage(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(24));
			writeBytes(varuint.encode(1));
			writeLittleEndianShort(this._endermanItemDamage.value);
		}
	}

	public pure nothrow @property @safe @nogc short age() {
		return _age.value;
	}

	public pure nothrow @property @safe short age(short value) {
		this._cached = false;
		this._age.value = value;
		if(!this._age.changed) {
			this._age.changed = true;
			this._changed ~= &this.encodeAge;
		}
		return value;
	}

	public pure nothrow @safe encodeAge(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(25));
			writeBytes(varuint.encode(1));
			writeLittleEndianShort(this._age.value);
		}
	}

	public pure nothrow @property @safe @nogc byte playerFlags() {
		return _playerFlags.value;
	}

	public pure nothrow @property @safe byte playerFlags(byte value) {
		this._cached = false;
		this._playerFlags.value = value;
		if(!this._playerFlags.changed) {
			this._playerFlags.changed = true;
			this._changed ~= &this.encodePlayerFlags;
		}
		return value;
	}

	public pure nothrow @safe encodePlayerFlags(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(27));
			writeBytes(varuint.encode(0));
			writeLittleEndianByte(this._playerFlags.value);
		}
	}

	public pure nothrow @property @safe bool asleep() {
		return _playerFlags.value._1;
	}

	public pure nothrow @property @safe bool asleep(bool value) {
		_playerFlags.value._1 = value;
		return value;
	}

	public pure nothrow @property @safe @nogc int playerIndex() {
		return _playerIndex.value;
	}

	public pure nothrow @property @safe int playerIndex(int value) {
		this._cached = false;
		this._playerIndex.value = value;
		if(!this._playerIndex.changed) {
			this._playerIndex.changed = true;
			this._changed ~= &this.encodePlayerIndex;
		}
		return value;
	}

	public pure nothrow @safe encodePlayerIndex(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(28));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._playerIndex.value));
		}
	}

	public pure nothrow @property @safe @nogc Tuple!(int, "x", int, "y", int, "z") bedPosition() {
		return _bedPosition.value;
	}

	public pure nothrow @property @safe Tuple!(int, "x", int, "y", int, "z") bedPosition(Tuple!(int, "x", int, "y", int, "z") value) {
		this._cached = false;
		this._bedPosition.value = value;
		if(!this._bedPosition.changed) {
			this._bedPosition.changed = true;
			this._changed ~= &this.encodeBedPosition;
		}
		return value;
	}

	public pure nothrow @safe encodeBedPosition(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(29));
			writeBytes(varuint.encode(6));
			writeBytes(varint.encode(this._bedPosition.value.x)); writeBytes(varint.encode(this._bedPosition.value.y)); writeBytes(varint.encode(this._bedPosition.value.z));
		}
	}

	public pure nothrow @property @safe @nogc float fireballPowerX() {
		return _fireballPowerX.value;
	}

	public pure nothrow @property @safe float fireballPowerX(float value) {
		this._cached = false;
		this._fireballPowerX.value = value;
		if(!this._fireballPowerX.changed) {
			this._fireballPowerX.changed = true;
			this._changed ~= &this.encodeFireballPowerX;
		}
		return value;
	}

	public pure nothrow @safe encodeFireballPowerX(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(30));
			writeBytes(varuint.encode(3));
			writeLittleEndianFloat(this._fireballPowerX.value);
		}
	}

	public pure nothrow @property @safe @nogc float fireballPowerY() {
		return _fireballPowerY.value;
	}

	public pure nothrow @property @safe float fireballPowerY(float value) {
		this._cached = false;
		this._fireballPowerY.value = value;
		if(!this._fireballPowerY.changed) {
			this._fireballPowerY.changed = true;
			this._changed ~= &this.encodeFireballPowerY;
		}
		return value;
	}

	public pure nothrow @safe encodeFireballPowerY(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(31));
			writeBytes(varuint.encode(3));
			writeLittleEndianFloat(this._fireballPowerY.value);
		}
	}

	public pure nothrow @property @safe @nogc float fireballPowerZ() {
		return _fireballPowerZ.value;
	}

	public pure nothrow @property @safe float fireballPowerZ(float value) {
		this._cached = false;
		this._fireballPowerZ.value = value;
		if(!this._fireballPowerZ.changed) {
			this._fireballPowerZ.changed = true;
			this._changed ~= &this.encodeFireballPowerZ;
		}
		return value;
	}

	public pure nothrow @safe encodeFireballPowerZ(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(32));
			writeBytes(varuint.encode(3));
			writeLittleEndianFloat(this._fireballPowerZ.value);
		}
	}

	public pure nothrow @property @safe @nogc short potionAuxValue() {
		return _potionAuxValue.value;
	}

	public pure nothrow @property @safe short potionAuxValue(short value) {
		this._cached = false;
		this._potionAuxValue.value = value;
		if(!this._potionAuxValue.changed) {
			this._potionAuxValue.changed = true;
			this._changed ~= &this.encodePotionAuxValue;
		}
		return value;
	}

	public pure nothrow @safe encodePotionAuxValue(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(37));
			writeBytes(varuint.encode(1));
			writeLittleEndianShort(this._potionAuxValue.value);
		}
	}

	public pure nothrow @property @safe @nogc long leadHolder() {
		return _leadHolder;
	}

	public pure nothrow @property @safe long leadHolder(long value) {
		this._cached = false;
		this._leadHolder = value;
		return value;
	}

	public pure nothrow @safe encodeLeadHolder(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(38));
			writeBytes(varuint.encode(7));
			writeBytes(varlong.encode(this._leadHolder));
		}
	}

	public pure nothrow @property @safe @nogc float scale() {
		return _scale.value;
	}

	public pure nothrow @property @safe float scale(float value) {
		this._cached = false;
		this._scale.value = value;
		if(!this._scale.changed) {
			this._scale.changed = true;
			this._changed ~= &this.encodeScale;
		}
		return value;
	}

	public pure nothrow @safe encodeScale(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(39));
			writeBytes(varuint.encode(3));
			writeLittleEndianFloat(this._scale.value);
		}
	}

	public pure nothrow @property @safe @nogc string interactiveTag() {
		return _interactiveTag.value;
	}

	public pure nothrow @property @safe string interactiveTag(string value) {
		this._cached = false;
		this._interactiveTag.value = value;
		if(!this._interactiveTag.changed) {
			this._interactiveTag.changed = true;
			this._changed ~= &this.encodeInteractiveTag;
		}
		return value;
	}

	public pure nothrow @safe encodeInteractiveTag(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(40));
			writeBytes(varuint.encode(4));
			writeBytes(varuint.encode(cast(uint)this._interactiveTag.value.length)); writeString(this._interactiveTag.value);
		}
	}

	public pure nothrow @property @safe @nogc string npcId() {
		return _npcId.value;
	}

	public pure nothrow @property @safe string npcId(string value) {
		this._cached = false;
		this._npcId.value = value;
		if(!this._npcId.changed) {
			this._npcId.changed = true;
			this._changed ~= &this.encodeNpcId;
		}
		return value;
	}

	public pure nothrow @safe encodeNpcId(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(41));
			writeBytes(varuint.encode(4));
			writeBytes(varuint.encode(cast(uint)this._npcId.value.length)); writeString(this._npcId.value);
		}
	}

	public pure nothrow @property @safe @nogc string interactiveTagUrl() {
		return _interactiveTagUrl.value;
	}

	public pure nothrow @property @safe string interactiveTagUrl(string value) {
		this._cached = false;
		this._interactiveTagUrl.value = value;
		if(!this._interactiveTagUrl.changed) {
			this._interactiveTagUrl.changed = true;
			this._changed ~= &this.encodeInteractiveTagUrl;
		}
		return value;
	}

	public pure nothrow @safe encodeInteractiveTagUrl(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(42));
			writeBytes(varuint.encode(4));
			writeBytes(varuint.encode(cast(uint)this._interactiveTagUrl.value.length)); writeString(this._interactiveTagUrl.value);
		}
	}

	public pure nothrow @property @safe @nogc short maxAir() {
		return _maxAir.value;
	}

	public pure nothrow @property @safe short maxAir(short value) {
		this._cached = false;
		this._maxAir.value = value;
		if(!this._maxAir.changed) {
			this._maxAir.changed = true;
			this._changed ~= &this.encodeMaxAir;
		}
		return value;
	}

	public pure nothrow @safe encodeMaxAir(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(43));
			writeBytes(varuint.encode(1));
			writeLittleEndianShort(this._maxAir.value);
		}
	}

	public pure nothrow @property @safe @nogc int markVariant() {
		return _markVariant.value;
	}

	public pure nothrow @property @safe int markVariant(int value) {
		this._cached = false;
		this._markVariant.value = value;
		if(!this._markVariant.changed) {
			this._markVariant.changed = true;
			this._changed ~= &this.encodeMarkVariant;
		}
		return value;
	}

	public pure nothrow @safe encodeMarkVariant(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(44));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._markVariant.value));
		}
	}

	public pure nothrow @property @safe @nogc Tuple!(int, "x", int, "y", int, "z") blockTarget() {
		return _blockTarget.value;
	}

	public pure nothrow @property @safe Tuple!(int, "x", int, "y", int, "z") blockTarget(Tuple!(int, "x", int, "y", int, "z") value) {
		this._cached = false;
		this._blockTarget.value = value;
		if(!this._blockTarget.changed) {
			this._blockTarget.changed = true;
			this._changed ~= &this.encodeBlockTarget;
		}
		return value;
	}

	public pure nothrow @safe encodeBlockTarget(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(48));
			writeBytes(varuint.encode(6));
			writeBytes(varint.encode(this._blockTarget.value.x)); writeBytes(varint.encode(this._blockTarget.value.y)); writeBytes(varint.encode(this._blockTarget.value.z));
		}
	}

	public pure nothrow @property @safe @nogc int invulnerableTime() {
		return _invulnerableTime.value;
	}

	public pure nothrow @property @safe int invulnerableTime(int value) {
		this._cached = false;
		this._invulnerableTime.value = value;
		if(!this._invulnerableTime.changed) {
			this._invulnerableTime.changed = true;
			this._changed ~= &this.encodeInvulnerableTime;
		}
		return value;
	}

	public pure nothrow @safe encodeInvulnerableTime(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(49));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._invulnerableTime.value));
		}
	}

	public pure nothrow @property @safe @nogc long centerHeadTarget() {
		return _centerHeadTarget.value;
	}

	public pure nothrow @property @safe long centerHeadTarget(long value) {
		this._cached = false;
		this._centerHeadTarget.value = value;
		if(!this._centerHeadTarget.changed) {
			this._centerHeadTarget.changed = true;
			this._changed ~= &this.encodeCenterHeadTarget;
		}
		return value;
	}

	public pure nothrow @safe encodeCenterHeadTarget(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(50));
			writeBytes(varuint.encode(7));
			writeBytes(varlong.encode(this._centerHeadTarget.value));
		}
	}

	public pure nothrow @property @safe @nogc long leftHeadTarget() {
		return _leftHeadTarget.value;
	}

	public pure nothrow @property @safe long leftHeadTarget(long value) {
		this._cached = false;
		this._leftHeadTarget.value = value;
		if(!this._leftHeadTarget.changed) {
			this._leftHeadTarget.changed = true;
			this._changed ~= &this.encodeLeftHeadTarget;
		}
		return value;
	}

	public pure nothrow @safe encodeLeftHeadTarget(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(51));
			writeBytes(varuint.encode(7));
			writeBytes(varlong.encode(this._leftHeadTarget.value));
		}
	}

	public pure nothrow @property @safe @nogc long rightHeadTarget() {
		return _rightHeadTarget.value;
	}

	public pure nothrow @property @safe long rightHeadTarget(long value) {
		this._cached = false;
		this._rightHeadTarget.value = value;
		if(!this._rightHeadTarget.changed) {
			this._rightHeadTarget.changed = true;
			this._changed ~= &this.encodeRightHeadTarget;
		}
		return value;
	}

	public pure nothrow @safe encodeRightHeadTarget(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(52));
			writeBytes(varuint.encode(7));
			writeBytes(varlong.encode(this._rightHeadTarget.value));
		}
	}

	public pure nothrow @property @safe @nogc float boundingBoxWidth() {
		return _boundingBoxWidth.value;
	}

	public pure nothrow @property @safe float boundingBoxWidth(float value) {
		this._cached = false;
		this._boundingBoxWidth.value = value;
		if(!this._boundingBoxWidth.changed) {
			this._boundingBoxWidth.changed = true;
			this._changed ~= &this.encodeBoundingBoxWidth;
		}
		return value;
	}

	public pure nothrow @safe encodeBoundingBoxWidth(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(54));
			writeBytes(varuint.encode(3));
			writeLittleEndianFloat(this._boundingBoxWidth.value);
		}
	}

	public pure nothrow @property @safe @nogc float boundingBoxHeight() {
		return _boundingBoxHeight.value;
	}

	public pure nothrow @property @safe float boundingBoxHeight(float value) {
		this._cached = false;
		this._boundingBoxHeight.value = value;
		if(!this._boundingBoxHeight.changed) {
			this._boundingBoxHeight.changed = true;
			this._changed ~= &this.encodeBoundingBoxHeight;
		}
		return value;
	}

	public pure nothrow @safe encodeBoundingBoxHeight(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(55));
			writeBytes(varuint.encode(3));
			writeLittleEndianFloat(this._boundingBoxHeight.value);
		}
	}

	public pure nothrow @property @safe @nogc int fuseLength() {
		return _fuseLength.value;
	}

	public pure nothrow @property @safe int fuseLength(int value) {
		this._cached = false;
		this._fuseLength.value = value;
		if(!this._fuseLength.changed) {
			this._fuseLength.changed = true;
			this._changed ~= &this.encodeFuseLength;
		}
		return value;
	}

	public pure nothrow @safe encodeFuseLength(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(56));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._fuseLength.value));
		}
	}

	public pure nothrow @property @safe @nogc Tuple!(float, "x", float, "y", float, "z") riderSeatPosition() {
		return _riderSeatPosition.value;
	}

	public pure nothrow @property @safe Tuple!(float, "x", float, "y", float, "z") riderSeatPosition(Tuple!(float, "x", float, "y", float, "z") value) {
		this._cached = false;
		this._riderSeatPosition.value = value;
		if(!this._riderSeatPosition.changed) {
			this._riderSeatPosition.changed = true;
			this._changed ~= &this.encodeRiderSeatPosition;
		}
		return value;
	}

	public pure nothrow @safe encodeRiderSeatPosition(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(57));
			writeBytes(varuint.encode(8));
			writeLittleEndianFloat(this._riderSeatPosition.value.x); writeLittleEndianFloat(this._riderSeatPosition.value.y); writeLittleEndianFloat(this._riderSeatPosition.value.z);
		}
	}

	public pure nothrow @property @safe @nogc byte riderRotationLocked() {
		return _riderRotationLocked.value;
	}

	public pure nothrow @property @safe byte riderRotationLocked(byte value) {
		this._cached = false;
		this._riderRotationLocked.value = value;
		if(!this._riderRotationLocked.changed) {
			this._riderRotationLocked.changed = true;
			this._changed ~= &this.encodeRiderRotationLocked;
		}
		return value;
	}

	public pure nothrow @safe encodeRiderRotationLocked(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(58));
			writeBytes(varuint.encode(0));
			writeLittleEndianByte(this._riderRotationLocked.value);
		}
	}

	public pure nothrow @property @safe @nogc float riderMaxRotation() {
		return _riderMaxRotation.value;
	}

	public pure nothrow @property @safe float riderMaxRotation(float value) {
		this._cached = false;
		this._riderMaxRotation.value = value;
		if(!this._riderMaxRotation.changed) {
			this._riderMaxRotation.changed = true;
			this._changed ~= &this.encodeRiderMaxRotation;
		}
		return value;
	}

	public pure nothrow @safe encodeRiderMaxRotation(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(59));
			writeBytes(varuint.encode(3));
			writeLittleEndianFloat(this._riderMaxRotation.value);
		}
	}

	public pure nothrow @property @safe @nogc float riderMinRotation() {
		return _riderMinRotation.value;
	}

	public pure nothrow @property @safe float riderMinRotation(float value) {
		this._cached = false;
		this._riderMinRotation.value = value;
		if(!this._riderMinRotation.changed) {
			this._riderMinRotation.changed = true;
			this._changed ~= &this.encodeRiderMinRotation;
		}
		return value;
	}

	public pure nothrow @safe encodeRiderMinRotation(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(60));
			writeBytes(varuint.encode(3));
			writeLittleEndianFloat(this._riderMinRotation.value);
		}
	}

	public pure nothrow @property @safe @nogc float areaEffectCloudRadius() {
		return _areaEffectCloudRadius.value;
	}

	public pure nothrow @property @safe float areaEffectCloudRadius(float value) {
		this._cached = false;
		this._areaEffectCloudRadius.value = value;
		if(!this._areaEffectCloudRadius.changed) {
			this._areaEffectCloudRadius.changed = true;
			this._changed ~= &this.encodeAreaEffectCloudRadius;
		}
		return value;
	}

	public pure nothrow @safe encodeAreaEffectCloudRadius(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(61));
			writeBytes(varuint.encode(3));
			writeLittleEndianFloat(this._areaEffectCloudRadius.value);
		}
	}

	public pure nothrow @property @safe @nogc int areaEffectCloudWaiting() {
		return _areaEffectCloudWaiting.value;
	}

	public pure nothrow @property @safe int areaEffectCloudWaiting(int value) {
		this._cached = false;
		this._areaEffectCloudWaiting.value = value;
		if(!this._areaEffectCloudWaiting.changed) {
			this._areaEffectCloudWaiting.changed = true;
			this._changed ~= &this.encodeAreaEffectCloudWaiting;
		}
		return value;
	}

	public pure nothrow @safe encodeAreaEffectCloudWaiting(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(62));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._areaEffectCloudWaiting.value));
		}
	}

	public pure nothrow @property @safe @nogc int areaEffectCloudParticle() {
		return _areaEffectCloudParticle.value;
	}

	public pure nothrow @property @safe int areaEffectCloudParticle(int value) {
		this._cached = false;
		this._areaEffectCloudParticle.value = value;
		if(!this._areaEffectCloudParticle.changed) {
			this._areaEffectCloudParticle.changed = true;
			this._changed ~= &this.encodeAreaEffectCloudParticle;
		}
		return value;
	}

	public pure nothrow @safe encodeAreaEffectCloudParticle(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(63));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._areaEffectCloudParticle.value));
		}
	}

	public pure nothrow @property @safe @nogc int shulkerPeakHeight() {
		return _shulkerPeakHeight.value;
	}

	public pure nothrow @property @safe int shulkerPeakHeight(int value) {
		this._cached = false;
		this._shulkerPeakHeight.value = value;
		if(!this._shulkerPeakHeight.changed) {
			this._shulkerPeakHeight.changed = true;
			this._changed ~= &this.encodeShulkerPeakHeight;
		}
		return value;
	}

	public pure nothrow @safe encodeShulkerPeakHeight(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(64));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._shulkerPeakHeight.value));
		}
	}

	public pure nothrow @property @safe @nogc byte shulkerDirection() {
		return _shulkerDirection.value;
	}

	public pure nothrow @property @safe byte shulkerDirection(byte value) {
		this._cached = false;
		this._shulkerDirection.value = value;
		if(!this._shulkerDirection.changed) {
			this._shulkerDirection.changed = true;
			this._changed ~= &this.encodeShulkerDirection;
		}
		return value;
	}

	public pure nothrow @safe encodeShulkerDirection(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(65));
			writeBytes(varuint.encode(0));
			writeLittleEndianByte(this._shulkerDirection.value);
		}
	}

	public pure nothrow @property @safe @nogc Tuple!(int, "x", int, "y", int, "z") shulkerAttachment() {
		return _shulkerAttachment.value;
	}

	public pure nothrow @property @safe Tuple!(int, "x", int, "y", int, "z") shulkerAttachment(Tuple!(int, "x", int, "y", int, "z") value) {
		this._cached = false;
		this._shulkerAttachment.value = value;
		if(!this._shulkerAttachment.changed) {
			this._shulkerAttachment.changed = true;
			this._changed ~= &this.encodeShulkerAttachment;
		}
		return value;
	}

	public pure nothrow @safe encodeShulkerAttachment(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(67));
			writeBytes(varuint.encode(6));
			writeBytes(varint.encode(this._shulkerAttachment.value.x)); writeBytes(varint.encode(this._shulkerAttachment.value.y)); writeBytes(varint.encode(this._shulkerAttachment.value.z));
		}
	}

	public pure nothrow @property @safe @nogc long tradingPlayer() {
		return _tradingPlayer.value;
	}

	public pure nothrow @property @safe long tradingPlayer(long value) {
		this._cached = false;
		this._tradingPlayer.value = value;
		if(!this._tradingPlayer.changed) {
			this._tradingPlayer.changed = true;
			this._changed ~= &this.encodeTradingPlayer;
		}
		return value;
	}

	public pure nothrow @safe encodeTradingPlayer(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(68));
			writeBytes(varuint.encode(7));
			writeBytes(varlong.encode(this._tradingPlayer.value));
		}
	}

	public pure nothrow @property @safe @nogc string commandBlockCommand() {
		return _commandBlockCommand.value;
	}

	public pure nothrow @property @safe string commandBlockCommand(string value) {
		this._cached = false;
		this._commandBlockCommand.value = value;
		if(!this._commandBlockCommand.changed) {
			this._commandBlockCommand.changed = true;
			this._changed ~= &this.encodeCommandBlockCommand;
		}
		return value;
	}

	public pure nothrow @safe encodeCommandBlockCommand(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(71));
			writeBytes(varuint.encode(4));
			writeBytes(varuint.encode(cast(uint)this._commandBlockCommand.value.length)); writeString(this._commandBlockCommand.value);
		}
	}

	public pure nothrow @property @safe @nogc string commandBlockLastOutput() {
		return _commandBlockLastOutput.value;
	}

	public pure nothrow @property @safe string commandBlockLastOutput(string value) {
		this._cached = false;
		this._commandBlockLastOutput.value = value;
		if(!this._commandBlockLastOutput.changed) {
			this._commandBlockLastOutput.changed = true;
			this._changed ~= &this.encodeCommandBlockLastOutput;
		}
		return value;
	}

	public pure nothrow @safe encodeCommandBlockLastOutput(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(72));
			writeBytes(varuint.encode(4));
			writeBytes(varuint.encode(cast(uint)this._commandBlockLastOutput.value.length)); writeString(this._commandBlockLastOutput.value);
		}
	}

	public pure nothrow @property @safe @nogc string commandBlockTrackOutput() {
		return _commandBlockTrackOutput.value;
	}

	public pure nothrow @property @safe string commandBlockTrackOutput(string value) {
		this._cached = false;
		this._commandBlockTrackOutput.value = value;
		if(!this._commandBlockTrackOutput.changed) {
			this._commandBlockTrackOutput.changed = true;
			this._changed ~= &this.encodeCommandBlockTrackOutput;
		}
		return value;
	}

	public pure nothrow @safe encodeCommandBlockTrackOutput(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(73));
			writeBytes(varuint.encode(4));
			writeBytes(varuint.encode(cast(uint)this._commandBlockTrackOutput.value.length)); writeString(this._commandBlockTrackOutput.value);
		}
	}

	public pure nothrow @property @safe @nogc byte controllingRiderSeatNumber() {
		return _controllingRiderSeatNumber.value;
	}

	public pure nothrow @property @safe byte controllingRiderSeatNumber(byte value) {
		this._cached = false;
		this._controllingRiderSeatNumber.value = value;
		if(!this._controllingRiderSeatNumber.changed) {
			this._controllingRiderSeatNumber.changed = true;
			this._changed ~= &this.encodeControllingRiderSeatNumber;
		}
		return value;
	}

	public pure nothrow @safe encodeControllingRiderSeatNumber(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(74));
			writeBytes(varuint.encode(0));
			writeLittleEndianByte(this._controllingRiderSeatNumber.value);
		}
	}

	public pure nothrow @property @safe @nogc int strength() {
		return _strength.value;
	}

	public pure nothrow @property @safe int strength(int value) {
		this._cached = false;
		this._strength.value = value;
		if(!this._strength.changed) {
			this._strength.changed = true;
			this._changed ~= &this.encodeStrength;
		}
		return value;
	}

	public pure nothrow @safe encodeStrength(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(75));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._strength.value));
		}
	}

	public pure nothrow @property @safe @nogc int maxStrength() {
		return _maxStrength.value;
	}

	public pure nothrow @property @safe int maxStrength(int value) {
		this._cached = false;
		this._maxStrength.value = value;
		if(!this._maxStrength.changed) {
			this._maxStrength.changed = true;
			this._changed ~= &this.encodeMaxStrength;
		}
		return value;
	}

	public pure nothrow @safe encodeMaxStrength(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(76));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._maxStrength.value));
		}
	}

	public pure nothrow @safe encode(Buffer buffer) {
		with(buffer) {
			if(this._cached) {
				buffer.writeBytes(this._cache);
			} else {
				immutable start = buffer._buffer.length;
				writeBytes(varuint.encode(cast(uint)this._changed.length));
				foreach(del ; this._changed) del(buffer);
				this._cached = true;
				this._cache = buffer._buffer[start..$];
			}
		}
	}

	public static pure nothrow @safe Metadata decode(Buffer buffer) {
		auto metadata = new Metadata();
		with(buffer) {
			uint id;
			size_t length=varuint.decode(_buffer, &_index);
			while(length-- > 0) {
				id=varuint.decode(_buffer, &_index);
				switch(varuint.decode(_buffer, &_index)) {
					case 0:
						byte _0;
						_0=readLittleEndianByte();
						metadata.decoded ~= DecodedMetadata.fromByte(id, _0);
						break;
					case 1:
						short _1;
						_1=readLittleEndianShort();
						metadata.decoded ~= DecodedMetadata.fromShort(id, _1);
						break;
					case 2:
						int _2;
						_2=varint.decode(_buffer, &_index);
						metadata.decoded ~= DecodedMetadata.fromInt(id, _2);
						break;
					case 3:
						float _3;
						_3=readLittleEndianFloat();
						metadata.decoded ~= DecodedMetadata.fromFloat(id, _3);
						break;
					case 4:
						string _4;
						uint xq=varuint.decode(_buffer, &_index); _4=readString(xq);
						metadata.decoded ~= DecodedMetadata.fromString(id, _4);
						break;
					case 5:
						sul.protocol.bedrock160.types.Slot _5;
						_5.decode(bufferInstance);
						metadata.decoded ~= DecodedMetadata.fromSlot(id, _5);
						break;
					case 6:
						Tuple!(int, "x", int, "y", int, "z") _6;
						_6.x=varint.decode(_buffer, &_index); _6.y=varint.decode(_buffer, &_index); _6.z=varint.decode(_buffer, &_index);
						metadata.decoded ~= DecodedMetadata.fromBlockPosition(id, _6);
						break;
					case 7:
						long _7;
						_7=varlong.decode(_buffer, &_index);
						metadata.decoded ~= DecodedMetadata.fromLong(id, _7);
						break;
					case 8:
						Tuple!(float, "x", float, "y", float, "z") _8;
						_8.x=readLittleEndianFloat(); _8.y=readLittleEndianFloat(); _8.z=readLittleEndianFloat();
						metadata.decoded ~= DecodedMetadata.fromEntityPosition(id, _8);
						break;
					default:
						break;
				}
			}
		}
		return metadata;
	}

}

class DecodedMetadata {

	public immutable uint id;
	public immutable uint type;

	union {
		byte byte_;
		short short_;
		int int_;
		float float_;
		string string_;
		sul.protocol.bedrock160.types.Slot slot;
		Tuple!(int, "x", int, "y", int, "z") block_position;
		long long_;
		Tuple!(float, "x", float, "y", float, "z") entity_position;
	}

	private pure nothrow @safe @nogc this(uint id, uint type) {
		this.id = id;
		this.type = type;
	}

	public static pure nothrow @trusted DecodedMetadata fromByte(uint id, byte value) {
		auto ret = new DecodedMetadata(id, 0);
		ret.byte_ = value;
		return ret;
	}

	public static pure nothrow @trusted DecodedMetadata fromShort(uint id, short value) {
		auto ret = new DecodedMetadata(id, 1);
		ret.short_ = value;
		return ret;
	}

	public static pure nothrow @trusted DecodedMetadata fromInt(uint id, int value) {
		auto ret = new DecodedMetadata(id, 2);
		ret.int_ = value;
		return ret;
	}

	public static pure nothrow @trusted DecodedMetadata fromFloat(uint id, float value) {
		auto ret = new DecodedMetadata(id, 3);
		ret.float_ = value;
		return ret;
	}

	public static pure nothrow @trusted DecodedMetadata fromString(uint id, string value) {
		auto ret = new DecodedMetadata(id, 4);
		ret.string_ = value;
		return ret;
	}

	public static pure nothrow @trusted DecodedMetadata fromSlot(uint id, sul.protocol.bedrock160.types.Slot value) {
		auto ret = new DecodedMetadata(id, 5);
		ret.slot = value;
		return ret;
	}

	public static pure nothrow @trusted DecodedMetadata fromBlockPosition(uint id, Tuple!(int, "x", int, "y", int, "z") value) {
		auto ret = new DecodedMetadata(id, 6);
		ret.block_position = value;
		return ret;
	}

	public static pure nothrow @trusted DecodedMetadata fromLong(uint id, long value) {
		auto ret = new DecodedMetadata(id, 7);
		ret.long_ = value;
		return ret;
	}

	public static pure nothrow @trusted DecodedMetadata fromEntityPosition(uint id, Tuple!(float, "x", float, "y", float, "z") value) {
		auto ret = new DecodedMetadata(id, 8);
		ret.entity_position = value;
		return ret;
	}

}