/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 */
module sul.metadata.minecraft110;

import sul.utils.buffer : Buffer;

class Metadata {

	public pure nothrow @safe @nogc ubyte[] encode() {
		return (ubyte[]).init;
	}

	public static pure nothrow @safe @nogc Metadata decode(Buffer buffer) {
		return null;
	}

}