/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/metadata/pocket110.xml
 */
module sul.metadata.pocket110;

import std.typecons : Tuple, tuple;

import sul.utils.buffer : Buffer;
import sul.utils.var;

static import sul.protocol.pocket110.types;

alias Changed(T) = Tuple!(T, "value", bool, "changed");

class Metadata {

	private bool _cached = false;
	private ubyte[] _cache;

	private void delegate(Buffer) pure nothrow @safe[] _changed;

	private long _entityFlags = cast(long)0;
	private Changed!(int) _health;
	private Changed!(int) _variant;
	private Changed!(byte) _color;
	private Changed!(string) _nametag;
	private Changed!(long) _owner = tuple(cast(long)-1, false);
	private Changed!(long) _target;
	private short _air = cast(short)0;
	private Changed!(int) _potionColor;
	private Changed!(byte) _potionAmbient;
	private Changed!(int) _hurtTime;
	private Changed!(int) _hurtDirection;
	private Changed!(float) _paddleTimeLeft;
	private Changed!(float) _paddleTimeRight;
	private Changed!(int) _experienceCount;
	private Changed!(byte) _slimeSize = tuple(cast(byte)1, false);
	private Changed!(short) _age;
	private Changed!(byte) _playerFlags;
	private Changed!(int) _playerIndex;
	private Changed!(Tuple!(int, "x", int, "y", int, "z")) _bedPosition;
	private Changed!(short) _potionAuxValue;
	private long _leadHolder = cast(long)-1;
	private Changed!(float) _scale = tuple(cast(float)1, false);
	private Changed!(string) _interactiveTag;
	private Changed!(string) _npcId;
	private Changed!(string) _interactiveTagUrl;
	private Changed!(short) _maxAir;
	private Changed!(int) _markVariant;
	private Changed!(int) _invulnerableTime;
	private Changed!(long) _centerHeadTarget;
	private Changed!(long) _leftHeadTarget;
	private Changed!(long) _rightHeadTarget;
	private Changed!(float) _boundingBoxWidth;
	private Changed!(float) _boundingBoxHeight;
	private Changed!(int) _fuseLength;
	private Changed!(Tuple!(float, "x", float, "y", float, "z")) _riderSeatPosition;
	private Changed!(byte) _riderRotationLocked;
	private Changed!(float) _riderMaxRotation;
	private Changed!(float) _riderMinRotation;
	private Changed!(float) _areaEffectCloudRadius = tuple(cast(float)0.5, false);
	private Changed!(int) _areaEffectCloudWaiting;
	private Changed!(int) _areaEffectCloudParticle;
	private Changed!(byte) _shukerDirection;
	private Changed!(Tuple!(int, "x", int, "y", int, "z")) _shulkerAttachment;
	private Changed!(long) _tradingPlayer;
	private Changed!(byte) _controllingRiderSeatNumber;
	private Changed!(int) _strength;
	private Changed!(int) _maxStrength;

	public pure nothrow @safe this() {
		this.reset();
	}

	public pure nothrow @safe void reset() {
		this._changed = [
			&this.encodeEntityFlags,
			&this.encodeAir,
			&this.encodeLeadHolder,
		];
	}

	public pure nothrow @property @safe @nogc long entityFlags() {
		return _entityFlags;
	}

	public pure nothrow @property @safe long entityFlags(long value) {
		this._cached = false;
		this._entityFlags = value;
		return value;
	}

	public pure nothrow @safe encodeEntityFlags(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(0));
			writeBytes(varuint.encode(7));
			writeBytes(varlong.encode(this._entityFlags));
		}
	}

	public pure nothrow @property @safe bool onFire() {
		return (_entityFlags >>> 0) & 1;
	}

	public pure nothrow @property @safe bool onFire(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 0));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 0));
		return value;
	}

	public pure nothrow @property @safe bool sneaking() {
		return (_entityFlags >>> 1) & 1;
	}

	public pure nothrow @property @safe bool sneaking(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 1));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 1));
		return value;
	}

	public pure nothrow @property @safe bool riding() {
		return (_entityFlags >>> 2) & 1;
	}

	public pure nothrow @property @safe bool riding(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 2));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 2));
		return value;
	}

	public pure nothrow @property @safe bool sprinting() {
		return (_entityFlags >>> 3) & 1;
	}

	public pure nothrow @property @safe bool sprinting(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 3));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 3));
		return value;
	}

	public pure nothrow @property @safe bool usingItem() {
		return (_entityFlags >>> 4) & 1;
	}

	public pure nothrow @property @safe bool usingItem(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 4));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 4));
		return value;
	}

	public pure nothrow @property @safe bool invisible() {
		return (_entityFlags >>> 5) & 1;
	}

	public pure nothrow @property @safe bool invisible(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 5));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 5));
		return value;
	}

	public pure nothrow @property @safe bool tempted() {
		return (_entityFlags >>> 6) & 1;
	}

	public pure nothrow @property @safe bool tempted(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 6));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 6));
		return value;
	}

	public pure nothrow @property @safe bool inLove() {
		return (_entityFlags >>> 7) & 1;
	}

	public pure nothrow @property @safe bool inLove(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 7));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 7));
		return value;
	}

	public pure nothrow @property @safe bool saddled() {
		return (_entityFlags >>> 8) & 1;
	}

	public pure nothrow @property @safe bool saddled(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 8));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 8));
		return value;
	}

	public pure nothrow @property @safe bool powered() {
		return (_entityFlags >>> 9) & 1;
	}

	public pure nothrow @property @safe bool powered(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 9));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 9));
		return value;
	}

	public pure nothrow @property @safe bool ignited() {
		return (_entityFlags >>> 10) & 1;
	}

	public pure nothrow @property @safe bool ignited(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 10));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 10));
		return value;
	}

	public pure nothrow @property @safe bool baby() {
		return (_entityFlags >>> 11) & 1;
	}

	public pure nothrow @property @safe bool baby(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 11));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 11));
		return value;
	}

	public pure nothrow @property @safe bool converting() {
		return (_entityFlags >>> 12) & 1;
	}

	public pure nothrow @property @safe bool converting(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 12));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 12));
		return value;
	}

	public pure nothrow @property @safe bool critical() {
		return (_entityFlags >>> 13) & 1;
	}

	public pure nothrow @property @safe bool critical(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 13));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 13));
		return value;
	}

	public pure nothrow @property @safe bool showNametag() {
		return (_entityFlags >>> 14) & 1;
	}

	public pure nothrow @property @safe bool showNametag(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 14));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 14));
		return value;
	}

	public pure nothrow @property @safe bool alwaysShowNametag() {
		return (_entityFlags >>> 15) & 1;
	}

	public pure nothrow @property @safe bool alwaysShowNametag(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 15));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 15));
		return value;
	}

	public pure nothrow @property @safe bool noAi() {
		return (_entityFlags >>> 16) & 1;
	}

	public pure nothrow @property @safe bool noAi(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 16));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 16));
		return value;
	}

	public pure nothrow @property @safe bool silent() {
		return (_entityFlags >>> 17) & 1;
	}

	public pure nothrow @property @safe bool silent(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 17));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 17));
		return value;
	}

	public pure nothrow @property @safe bool climbing() {
		return (_entityFlags >>> 18) & 1;
	}

	public pure nothrow @property @safe bool climbing(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 18));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 18));
		return value;
	}

	public pure nothrow @property @safe bool canClimb() {
		return (_entityFlags >>> 19) & 1;
	}

	public pure nothrow @property @safe bool canClimb(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 19));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 19));
		return value;
	}

	public pure nothrow @property @safe bool canSwim() {
		return (_entityFlags >>> 20) & 1;
	}

	public pure nothrow @property @safe bool canSwim(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 20));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 20));
		return value;
	}

	public pure nothrow @property @safe bool canFly() {
		return (_entityFlags >>> 21) & 1;
	}

	public pure nothrow @property @safe bool canFly(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 21));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 21));
		return value;
	}

	public pure nothrow @property @safe bool resting() {
		return (_entityFlags >>> 22) & 1;
	}

	public pure nothrow @property @safe bool resting(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 22));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 22));
		return value;
	}

	public pure nothrow @property @safe bool sitting() {
		return (_entityFlags >>> 23) & 1;
	}

	public pure nothrow @property @safe bool sitting(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 23));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 23));
		return value;
	}

	public pure nothrow @property @safe bool angry() {
		return (_entityFlags >>> 24) & 1;
	}

	public pure nothrow @property @safe bool angry(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 24));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 24));
		return value;
	}

	public pure nothrow @property @safe bool interested() {
		return (_entityFlags >>> 25) & 1;
	}

	public pure nothrow @property @safe bool interested(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 25));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 25));
		return value;
	}

	public pure nothrow @property @safe bool charged() {
		return (_entityFlags >>> 26) & 1;
	}

	public pure nothrow @property @safe bool charged(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 26));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 26));
		return value;
	}

	public pure nothrow @property @safe bool tamed() {
		return (_entityFlags >>> 27) & 1;
	}

	public pure nothrow @property @safe bool tamed(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 27));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 27));
		return value;
	}

	public pure nothrow @property @safe bool leashed() {
		return (_entityFlags >>> 28) & 1;
	}

	public pure nothrow @property @safe bool leashed(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 28));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 28));
		return value;
	}

	public pure nothrow @property @safe bool sheared() {
		return (_entityFlags >>> 29) & 1;
	}

	public pure nothrow @property @safe bool sheared(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 29));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 29));
		return value;
	}

	public pure nothrow @property @safe bool gliding() {
		return (_entityFlags >>> 30) & 1;
	}

	public pure nothrow @property @safe bool gliding(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 30));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 30));
		return value;
	}

	public pure nothrow @property @safe bool elder() {
		return (_entityFlags >>> 31) & 1;
	}

	public pure nothrow @property @safe bool elder(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 31));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 31));
		return value;
	}

	public pure nothrow @property @safe bool moving() {
		return (_entityFlags >>> 32) & 1;
	}

	public pure nothrow @property @safe bool moving(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 32));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 32));
		return value;
	}

	public pure nothrow @property @safe bool breathing() {
		return (_entityFlags >>> 33) & 1;
	}

	public pure nothrow @property @safe bool breathing(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 33));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 33));
		return value;
	}

	public pure nothrow @property @safe bool chested() {
		return (_entityFlags >>> 34) & 1;
	}

	public pure nothrow @property @safe bool chested(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 34));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 34));
		return value;
	}

	public pure nothrow @property @safe bool stackable() {
		return (_entityFlags >>> 35) & 1;
	}

	public pure nothrow @property @safe bool stackable(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 35));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 35));
		return value;
	}

	public pure nothrow @property @safe bool showbase() {
		return (_entityFlags >>> 36) & 1;
	}

	public pure nothrow @property @safe bool showbase(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 36));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 36));
		return value;
	}

	public pure nothrow @property @safe bool rearing() {
		return (_entityFlags >>> 37) & 1;
	}

	public pure nothrow @property @safe bool rearing(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 37));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 37));
		return value;
	}

	public pure nothrow @property @safe bool vibrating() {
		return (_entityFlags >>> 38) & 1;
	}

	public pure nothrow @property @safe bool vibrating(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 38));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 38));
		return value;
	}

	public pure nothrow @property @safe bool idling() {
		return (_entityFlags >>> 39) & 1;
	}

	public pure nothrow @property @safe bool idling(bool value) {
		if(value) entityFlags = cast(long)(_entityFlags | (cast(long)true << 39));
		else entityFlags = cast(long)(_entityFlags & ~(cast(long)true << 39));
		return value;
	}

	public pure nothrow @property @safe @nogc int health() {
		return _health.value;
	}

	public pure nothrow @property @safe int health(int value) {
		this._cached = false;
		this._health.value = value;
		if(!this._health.changed) {
			this._health.changed = true;
			this._changed ~= &this.encodeHealth;
		}
		return value;
	}

	public pure nothrow @safe encodeHealth(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(1));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._health.value));
		}
	}

	public pure nothrow @property @safe @nogc int variant() {
		return _variant.value;
	}

	public pure nothrow @property @safe int variant(int value) {
		this._cached = false;
		this._variant.value = value;
		if(!this._variant.changed) {
			this._variant.changed = true;
			this._changed ~= &this.encodeVariant;
		}
		return value;
	}

	public pure nothrow @safe encodeVariant(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(2));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._variant.value));
		}
	}

	public pure nothrow @property @safe @nogc byte color() {
		return _color.value;
	}

	public pure nothrow @property @safe byte color(byte value) {
		this._cached = false;
		this._color.value = value;
		if(!this._color.changed) {
			this._color.changed = true;
			this._changed ~= &this.encodeColor;
		}
		return value;
	}

	public pure nothrow @safe encodeColor(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(3));
			writeBytes(varuint.encode(0));
			writeBigEndianByte(this._color.value);
		}
	}

	public pure nothrow @property @safe @nogc string nametag() {
		return _nametag.value;
	}

	public pure nothrow @property @safe string nametag(string value) {
		this._cached = false;
		this._nametag.value = value;
		if(!this._nametag.changed) {
			this._nametag.changed = true;
			this._changed ~= &this.encodeNametag;
		}
		return value;
	}

	public pure nothrow @safe encodeNametag(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(4));
			writeBytes(varuint.encode(4));
			writeBytes(varuint.encode(cast(uint)this._nametag.value.length)); writeString(this._nametag.value);
		}
	}

	public pure nothrow @property @safe @nogc long owner() {
		return _owner.value;
	}

	public pure nothrow @property @safe long owner(long value) {
		this._cached = false;
		this._owner.value = value;
		if(!this._owner.changed) {
			this._owner.changed = true;
			this._changed ~= &this.encodeOwner;
		}
		return value;
	}

	public pure nothrow @safe encodeOwner(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(5));
			writeBytes(varuint.encode(7));
			writeBytes(varlong.encode(this._owner.value));
		}
	}

	public pure nothrow @property @safe @nogc long target() {
		return _target.value;
	}

	public pure nothrow @property @safe long target(long value) {
		this._cached = false;
		this._target.value = value;
		if(!this._target.changed) {
			this._target.changed = true;
			this._changed ~= &this.encodeTarget;
		}
		return value;
	}

	public pure nothrow @safe encodeTarget(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(6));
			writeBytes(varuint.encode(7));
			writeBytes(varlong.encode(this._target.value));
		}
	}

	public pure nothrow @property @safe @nogc short air() {
		return _air;
	}

	public pure nothrow @property @safe short air(short value) {
		this._cached = false;
		this._air = value;
		return value;
	}

	public pure nothrow @safe encodeAir(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(7));
			writeBytes(varuint.encode(1));
			writeLittleEndianShort(this._air);
		}
	}

	public pure nothrow @property @safe @nogc int potionColor() {
		return _potionColor.value;
	}

	public pure nothrow @property @safe int potionColor(int value) {
		this._cached = false;
		this._potionColor.value = value;
		if(!this._potionColor.changed) {
			this._potionColor.changed = true;
			this._changed ~= &this.encodePotionColor;
		}
		return value;
	}

	public pure nothrow @safe encodePotionColor(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(8));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._potionColor.value));
		}
	}

	public pure nothrow @property @safe @nogc byte potionAmbient() {
		return _potionAmbient.value;
	}

	public pure nothrow @property @safe byte potionAmbient(byte value) {
		this._cached = false;
		this._potionAmbient.value = value;
		if(!this._potionAmbient.changed) {
			this._potionAmbient.changed = true;
			this._changed ~= &this.encodePotionAmbient;
		}
		return value;
	}

	public pure nothrow @safe encodePotionAmbient(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(9));
			writeBytes(varuint.encode(0));
			writeBigEndianByte(this._potionAmbient.value);
		}
	}

	public pure nothrow @property @safe @nogc int hurtTime() {
		return _hurtTime.value;
	}

	public pure nothrow @property @safe int hurtTime(int value) {
		this._cached = false;
		this._hurtTime.value = value;
		if(!this._hurtTime.changed) {
			this._hurtTime.changed = true;
			this._changed ~= &this.encodeHurtTime;
		}
		return value;
	}

	public pure nothrow @safe encodeHurtTime(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(11));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._hurtTime.value));
		}
	}

	public pure nothrow @property @safe @nogc int hurtDirection() {
		return _hurtDirection.value;
	}

	public pure nothrow @property @safe int hurtDirection(int value) {
		this._cached = false;
		this._hurtDirection.value = value;
		if(!this._hurtDirection.changed) {
			this._hurtDirection.changed = true;
			this._changed ~= &this.encodeHurtDirection;
		}
		return value;
	}

	public pure nothrow @safe encodeHurtDirection(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(12));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._hurtDirection.value));
		}
	}

	public pure nothrow @property @safe @nogc float paddleTimeLeft() {
		return _paddleTimeLeft.value;
	}

	public pure nothrow @property @safe float paddleTimeLeft(float value) {
		this._cached = false;
		this._paddleTimeLeft.value = value;
		if(!this._paddleTimeLeft.changed) {
			this._paddleTimeLeft.changed = true;
			this._changed ~= &this.encodePaddleTimeLeft;
		}
		return value;
	}

	public pure nothrow @safe encodePaddleTimeLeft(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(13));
			writeBytes(varuint.encode(3));
			writeLittleEndianFloat(this._paddleTimeLeft.value);
		}
	}

	public pure nothrow @property @safe @nogc float paddleTimeRight() {
		return _paddleTimeRight.value;
	}

	public pure nothrow @property @safe float paddleTimeRight(float value) {
		this._cached = false;
		this._paddleTimeRight.value = value;
		if(!this._paddleTimeRight.changed) {
			this._paddleTimeRight.changed = true;
			this._changed ~= &this.encodePaddleTimeRight;
		}
		return value;
	}

	public pure nothrow @safe encodePaddleTimeRight(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(14));
			writeBytes(varuint.encode(3));
			writeLittleEndianFloat(this._paddleTimeRight.value);
		}
	}

	public pure nothrow @property @safe @nogc int experienceCount() {
		return _experienceCount.value;
	}

	public pure nothrow @property @safe int experienceCount(int value) {
		this._cached = false;
		this._experienceCount.value = value;
		if(!this._experienceCount.changed) {
			this._experienceCount.changed = true;
			this._changed ~= &this.encodeExperienceCount;
		}
		return value;
	}

	public pure nothrow @safe encodeExperienceCount(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(15));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._experienceCount.value));
		}
	}

	public pure nothrow @property @safe @nogc byte slimeSize() {
		return _slimeSize.value;
	}

	public pure nothrow @property @safe byte slimeSize(byte value) {
		this._cached = false;
		this._slimeSize.value = value;
		if(!this._slimeSize.changed) {
			this._slimeSize.changed = true;
			this._changed ~= &this.encodeSlimeSize;
		}
		return value;
	}

	public pure nothrow @safe encodeSlimeSize(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(16));
			writeBytes(varuint.encode(0));
			writeBigEndianByte(this._slimeSize.value);
		}
	}

	public pure nothrow @property @safe @nogc short age() {
		return _age.value;
	}

	public pure nothrow @property @safe short age(short value) {
		this._cached = false;
		this._age.value = value;
		if(!this._age.changed) {
			this._age.changed = true;
			this._changed ~= &this.encodeAge;
		}
		return value;
	}

	public pure nothrow @safe encodeAge(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(25));
			writeBytes(varuint.encode(1));
			writeLittleEndianShort(this._age.value);
		}
	}

	public pure nothrow @property @safe @nogc byte playerFlags() {
		return _playerFlags.value;
	}

	public pure nothrow @property @safe byte playerFlags(byte value) {
		this._cached = false;
		this._playerFlags.value = value;
		if(!this._playerFlags.changed) {
			this._playerFlags.changed = true;
			this._changed ~= &this.encodePlayerFlags;
		}
		return value;
	}

	public pure nothrow @safe encodePlayerFlags(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(27));
			writeBytes(varuint.encode(0));
			writeBigEndianByte(this._playerFlags.value);
		}
	}

	public pure nothrow @property @safe bool asleep() {
		return (_playerFlags.value >>> 1) & 1;
	}

	public pure nothrow @property @safe bool asleep(bool value) {
		if(value) playerFlags = cast(byte)(_playerFlags.value | (cast(byte)true << 1));
		else playerFlags = cast(byte)(_playerFlags.value & ~(cast(byte)true << 1));
		return value;
	}

	public pure nothrow @property @safe @nogc int playerIndex() {
		return _playerIndex.value;
	}

	public pure nothrow @property @safe int playerIndex(int value) {
		this._cached = false;
		this._playerIndex.value = value;
		if(!this._playerIndex.changed) {
			this._playerIndex.changed = true;
			this._changed ~= &this.encodePlayerIndex;
		}
		return value;
	}

	public pure nothrow @safe encodePlayerIndex(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(28));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._playerIndex.value));
		}
	}

	public pure nothrow @property @safe @nogc Tuple!(int, "x", int, "y", int, "z") bedPosition() {
		return _bedPosition.value;
	}

	public pure nothrow @property @safe Tuple!(int, "x", int, "y", int, "z") bedPosition(Tuple!(int, "x", int, "y", int, "z") value) {
		this._cached = false;
		this._bedPosition.value = value;
		if(!this._bedPosition.changed) {
			this._bedPosition.changed = true;
			this._changed ~= &this.encodeBedPosition;
		}
		return value;
	}

	public pure nothrow @safe encodeBedPosition(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(29));
			writeBytes(varuint.encode(6));
			writeBytes(varint.encode(this._bedPosition.value.x)); writeBytes(varint.encode(this._bedPosition.value.y)); writeBytes(varint.encode(this._bedPosition.value.z));
		}
	}

	public pure nothrow @property @safe @nogc short potionAuxValue() {
		return _potionAuxValue.value;
	}

	public pure nothrow @property @safe short potionAuxValue(short value) {
		this._cached = false;
		this._potionAuxValue.value = value;
		if(!this._potionAuxValue.changed) {
			this._potionAuxValue.changed = true;
			this._changed ~= &this.encodePotionAuxValue;
		}
		return value;
	}

	public pure nothrow @safe encodePotionAuxValue(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(37));
			writeBytes(varuint.encode(1));
			writeLittleEndianShort(this._potionAuxValue.value);
		}
	}

	public pure nothrow @property @safe @nogc long leadHolder() {
		return _leadHolder;
	}

	public pure nothrow @property @safe long leadHolder(long value) {
		this._cached = false;
		this._leadHolder = value;
		return value;
	}

	public pure nothrow @safe encodeLeadHolder(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(38));
			writeBytes(varuint.encode(7));
			writeBytes(varlong.encode(this._leadHolder));
		}
	}

	public pure nothrow @property @safe @nogc float scale() {
		return _scale.value;
	}

	public pure nothrow @property @safe float scale(float value) {
		this._cached = false;
		this._scale.value = value;
		if(!this._scale.changed) {
			this._scale.changed = true;
			this._changed ~= &this.encodeScale;
		}
		return value;
	}

	public pure nothrow @safe encodeScale(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(39));
			writeBytes(varuint.encode(3));
			writeLittleEndianFloat(this._scale.value);
		}
	}

	public pure nothrow @property @safe @nogc string interactiveTag() {
		return _interactiveTag.value;
	}

	public pure nothrow @property @safe string interactiveTag(string value) {
		this._cached = false;
		this._interactiveTag.value = value;
		if(!this._interactiveTag.changed) {
			this._interactiveTag.changed = true;
			this._changed ~= &this.encodeInteractiveTag;
		}
		return value;
	}

	public pure nothrow @safe encodeInteractiveTag(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(40));
			writeBytes(varuint.encode(4));
			writeBytes(varuint.encode(cast(uint)this._interactiveTag.value.length)); writeString(this._interactiveTag.value);
		}
	}

	public pure nothrow @property @safe @nogc string npcId() {
		return _npcId.value;
	}

	public pure nothrow @property @safe string npcId(string value) {
		this._cached = false;
		this._npcId.value = value;
		if(!this._npcId.changed) {
			this._npcId.changed = true;
			this._changed ~= &this.encodeNpcId;
		}
		return value;
	}

	public pure nothrow @safe encodeNpcId(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(41));
			writeBytes(varuint.encode(4));
			writeBytes(varuint.encode(cast(uint)this._npcId.value.length)); writeString(this._npcId.value);
		}
	}

	public pure nothrow @property @safe @nogc string interactiveTagUrl() {
		return _interactiveTagUrl.value;
	}

	public pure nothrow @property @safe string interactiveTagUrl(string value) {
		this._cached = false;
		this._interactiveTagUrl.value = value;
		if(!this._interactiveTagUrl.changed) {
			this._interactiveTagUrl.changed = true;
			this._changed ~= &this.encodeInteractiveTagUrl;
		}
		return value;
	}

	public pure nothrow @safe encodeInteractiveTagUrl(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(43));
			writeBytes(varuint.encode(4));
			writeBytes(varuint.encode(cast(uint)this._interactiveTagUrl.value.length)); writeString(this._interactiveTagUrl.value);
		}
	}

	public pure nothrow @property @safe @nogc short maxAir() {
		return _maxAir.value;
	}

	public pure nothrow @property @safe short maxAir(short value) {
		this._cached = false;
		this._maxAir.value = value;
		if(!this._maxAir.changed) {
			this._maxAir.changed = true;
			this._changed ~= &this.encodeMaxAir;
		}
		return value;
	}

	public pure nothrow @safe encodeMaxAir(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(44));
			writeBytes(varuint.encode(1));
			writeLittleEndianShort(this._maxAir.value);
		}
	}

	public pure nothrow @property @safe @nogc int markVariant() {
		return _markVariant.value;
	}

	public pure nothrow @property @safe int markVariant(int value) {
		this._cached = false;
		this._markVariant.value = value;
		if(!this._markVariant.changed) {
			this._markVariant.changed = true;
			this._changed ~= &this.encodeMarkVariant;
		}
		return value;
	}

	public pure nothrow @safe encodeMarkVariant(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(45));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._markVariant.value));
		}
	}

	public pure nothrow @property @safe @nogc int invulnerableTime() {
		return _invulnerableTime.value;
	}

	public pure nothrow @property @safe int invulnerableTime(int value) {
		this._cached = false;
		this._invulnerableTime.value = value;
		if(!this._invulnerableTime.changed) {
			this._invulnerableTime.changed = true;
			this._changed ~= &this.encodeInvulnerableTime;
		}
		return value;
	}

	public pure nothrow @safe encodeInvulnerableTime(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(49));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._invulnerableTime.value));
		}
	}

	public pure nothrow @property @safe @nogc long centerHeadTarget() {
		return _centerHeadTarget.value;
	}

	public pure nothrow @property @safe long centerHeadTarget(long value) {
		this._cached = false;
		this._centerHeadTarget.value = value;
		if(!this._centerHeadTarget.changed) {
			this._centerHeadTarget.changed = true;
			this._changed ~= &this.encodeCenterHeadTarget;
		}
		return value;
	}

	public pure nothrow @safe encodeCenterHeadTarget(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(50));
			writeBytes(varuint.encode(7));
			writeBytes(varlong.encode(this._centerHeadTarget.value));
		}
	}

	public pure nothrow @property @safe @nogc long leftHeadTarget() {
		return _leftHeadTarget.value;
	}

	public pure nothrow @property @safe long leftHeadTarget(long value) {
		this._cached = false;
		this._leftHeadTarget.value = value;
		if(!this._leftHeadTarget.changed) {
			this._leftHeadTarget.changed = true;
			this._changed ~= &this.encodeLeftHeadTarget;
		}
		return value;
	}

	public pure nothrow @safe encodeLeftHeadTarget(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(51));
			writeBytes(varuint.encode(7));
			writeBytes(varlong.encode(this._leftHeadTarget.value));
		}
	}

	public pure nothrow @property @safe @nogc long rightHeadTarget() {
		return _rightHeadTarget.value;
	}

	public pure nothrow @property @safe long rightHeadTarget(long value) {
		this._cached = false;
		this._rightHeadTarget.value = value;
		if(!this._rightHeadTarget.changed) {
			this._rightHeadTarget.changed = true;
			this._changed ~= &this.encodeRightHeadTarget;
		}
		return value;
	}

	public pure nothrow @safe encodeRightHeadTarget(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(52));
			writeBytes(varuint.encode(7));
			writeBytes(varlong.encode(this._rightHeadTarget.value));
		}
	}

	public pure nothrow @property @safe @nogc float boundingBoxWidth() {
		return _boundingBoxWidth.value;
	}

	public pure nothrow @property @safe float boundingBoxWidth(float value) {
		this._cached = false;
		this._boundingBoxWidth.value = value;
		if(!this._boundingBoxWidth.changed) {
			this._boundingBoxWidth.changed = true;
			this._changed ~= &this.encodeBoundingBoxWidth;
		}
		return value;
	}

	public pure nothrow @safe encodeBoundingBoxWidth(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(54));
			writeBytes(varuint.encode(3));
			writeLittleEndianFloat(this._boundingBoxWidth.value);
		}
	}

	public pure nothrow @property @safe @nogc float boundingBoxHeight() {
		return _boundingBoxHeight.value;
	}

	public pure nothrow @property @safe float boundingBoxHeight(float value) {
		this._cached = false;
		this._boundingBoxHeight.value = value;
		if(!this._boundingBoxHeight.changed) {
			this._boundingBoxHeight.changed = true;
			this._changed ~= &this.encodeBoundingBoxHeight;
		}
		return value;
	}

	public pure nothrow @safe encodeBoundingBoxHeight(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(55));
			writeBytes(varuint.encode(3));
			writeLittleEndianFloat(this._boundingBoxHeight.value);
		}
	}

	public pure nothrow @property @safe @nogc int fuseLength() {
		return _fuseLength.value;
	}

	public pure nothrow @property @safe int fuseLength(int value) {
		this._cached = false;
		this._fuseLength.value = value;
		if(!this._fuseLength.changed) {
			this._fuseLength.changed = true;
			this._changed ~= &this.encodeFuseLength;
		}
		return value;
	}

	public pure nothrow @safe encodeFuseLength(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(56));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._fuseLength.value));
		}
	}

	public pure nothrow @property @safe @nogc Tuple!(float, "x", float, "y", float, "z") riderSeatPosition() {
		return _riderSeatPosition.value;
	}

	public pure nothrow @property @safe Tuple!(float, "x", float, "y", float, "z") riderSeatPosition(Tuple!(float, "x", float, "y", float, "z") value) {
		this._cached = false;
		this._riderSeatPosition.value = value;
		if(!this._riderSeatPosition.changed) {
			this._riderSeatPosition.changed = true;
			this._changed ~= &this.encodeRiderSeatPosition;
		}
		return value;
	}

	public pure nothrow @safe encodeRiderSeatPosition(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(57));
			writeBytes(varuint.encode(8));
			writeLittleEndianFloat(this._riderSeatPosition.value.x); writeLittleEndianFloat(this._riderSeatPosition.value.y); writeLittleEndianFloat(this._riderSeatPosition.value.z);
		}
	}

	public pure nothrow @property @safe @nogc byte riderRotationLocked() {
		return _riderRotationLocked.value;
	}

	public pure nothrow @property @safe byte riderRotationLocked(byte value) {
		this._cached = false;
		this._riderRotationLocked.value = value;
		if(!this._riderRotationLocked.changed) {
			this._riderRotationLocked.changed = true;
			this._changed ~= &this.encodeRiderRotationLocked;
		}
		return value;
	}

	public pure nothrow @safe encodeRiderRotationLocked(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(58));
			writeBytes(varuint.encode(0));
			writeBigEndianByte(this._riderRotationLocked.value);
		}
	}

	public pure nothrow @property @safe @nogc float riderMaxRotation() {
		return _riderMaxRotation.value;
	}

	public pure nothrow @property @safe float riderMaxRotation(float value) {
		this._cached = false;
		this._riderMaxRotation.value = value;
		if(!this._riderMaxRotation.changed) {
			this._riderMaxRotation.changed = true;
			this._changed ~= &this.encodeRiderMaxRotation;
		}
		return value;
	}

	public pure nothrow @safe encodeRiderMaxRotation(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(59));
			writeBytes(varuint.encode(3));
			writeLittleEndianFloat(this._riderMaxRotation.value);
		}
	}

	public pure nothrow @property @safe @nogc float riderMinRotation() {
		return _riderMinRotation.value;
	}

	public pure nothrow @property @safe float riderMinRotation(float value) {
		this._cached = false;
		this._riderMinRotation.value = value;
		if(!this._riderMinRotation.changed) {
			this._riderMinRotation.changed = true;
			this._changed ~= &this.encodeRiderMinRotation;
		}
		return value;
	}

	public pure nothrow @safe encodeRiderMinRotation(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(60));
			writeBytes(varuint.encode(3));
			writeLittleEndianFloat(this._riderMinRotation.value);
		}
	}

	public pure nothrow @property @safe @nogc float areaEffectCloudRadius() {
		return _areaEffectCloudRadius.value;
	}

	public pure nothrow @property @safe float areaEffectCloudRadius(float value) {
		this._cached = false;
		this._areaEffectCloudRadius.value = value;
		if(!this._areaEffectCloudRadius.changed) {
			this._areaEffectCloudRadius.changed = true;
			this._changed ~= &this.encodeAreaEffectCloudRadius;
		}
		return value;
	}

	public pure nothrow @safe encodeAreaEffectCloudRadius(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(61));
			writeBytes(varuint.encode(3));
			writeLittleEndianFloat(this._areaEffectCloudRadius.value);
		}
	}

	public pure nothrow @property @safe @nogc int areaEffectCloudWaiting() {
		return _areaEffectCloudWaiting.value;
	}

	public pure nothrow @property @safe int areaEffectCloudWaiting(int value) {
		this._cached = false;
		this._areaEffectCloudWaiting.value = value;
		if(!this._areaEffectCloudWaiting.changed) {
			this._areaEffectCloudWaiting.changed = true;
			this._changed ~= &this.encodeAreaEffectCloudWaiting;
		}
		return value;
	}

	public pure nothrow @safe encodeAreaEffectCloudWaiting(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(62));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._areaEffectCloudWaiting.value));
		}
	}

	public pure nothrow @property @safe @nogc int areaEffectCloudParticle() {
		return _areaEffectCloudParticle.value;
	}

	public pure nothrow @property @safe int areaEffectCloudParticle(int value) {
		this._cached = false;
		this._areaEffectCloudParticle.value = value;
		if(!this._areaEffectCloudParticle.changed) {
			this._areaEffectCloudParticle.changed = true;
			this._changed ~= &this.encodeAreaEffectCloudParticle;
		}
		return value;
	}

	public pure nothrow @safe encodeAreaEffectCloudParticle(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(63));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._areaEffectCloudParticle.value));
		}
	}

	public pure nothrow @property @safe @nogc byte shukerDirection() {
		return _shukerDirection.value;
	}

	public pure nothrow @property @safe byte shukerDirection(byte value) {
		this._cached = false;
		this._shukerDirection.value = value;
		if(!this._shukerDirection.changed) {
			this._shukerDirection.changed = true;
			this._changed ~= &this.encodeShukerDirection;
		}
		return value;
	}

	public pure nothrow @safe encodeShukerDirection(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(65));
			writeBytes(varuint.encode(0));
			writeBigEndianByte(this._shukerDirection.value);
		}
	}

	public pure nothrow @property @safe @nogc Tuple!(int, "x", int, "y", int, "z") shulkerAttachment() {
		return _shulkerAttachment.value;
	}

	public pure nothrow @property @safe Tuple!(int, "x", int, "y", int, "z") shulkerAttachment(Tuple!(int, "x", int, "y", int, "z") value) {
		this._cached = false;
		this._shulkerAttachment.value = value;
		if(!this._shulkerAttachment.changed) {
			this._shulkerAttachment.changed = true;
			this._changed ~= &this.encodeShulkerAttachment;
		}
		return value;
	}

	public pure nothrow @safe encodeShulkerAttachment(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(67));
			writeBytes(varuint.encode(6));
			writeBytes(varint.encode(this._shulkerAttachment.value.x)); writeBytes(varint.encode(this._shulkerAttachment.value.y)); writeBytes(varint.encode(this._shulkerAttachment.value.z));
		}
	}

	public pure nothrow @property @safe @nogc long tradingPlayer() {
		return _tradingPlayer.value;
	}

	public pure nothrow @property @safe long tradingPlayer(long value) {
		this._cached = false;
		this._tradingPlayer.value = value;
		if(!this._tradingPlayer.changed) {
			this._tradingPlayer.changed = true;
			this._changed ~= &this.encodeTradingPlayer;
		}
		return value;
	}

	public pure nothrow @safe encodeTradingPlayer(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(68));
			writeBytes(varuint.encode(7));
			writeBytes(varlong.encode(this._tradingPlayer.value));
		}
	}

	public pure nothrow @property @safe @nogc byte controllingRiderSeatNumber() {
		return _controllingRiderSeatNumber.value;
	}

	public pure nothrow @property @safe byte controllingRiderSeatNumber(byte value) {
		this._cached = false;
		this._controllingRiderSeatNumber.value = value;
		if(!this._controllingRiderSeatNumber.changed) {
			this._controllingRiderSeatNumber.changed = true;
			this._changed ~= &this.encodeControllingRiderSeatNumber;
		}
		return value;
	}

	public pure nothrow @safe encodeControllingRiderSeatNumber(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(74));
			writeBytes(varuint.encode(0));
			writeBigEndianByte(this._controllingRiderSeatNumber.value);
		}
	}

	public pure nothrow @property @safe @nogc int strength() {
		return _strength.value;
	}

	public pure nothrow @property @safe int strength(int value) {
		this._cached = false;
		this._strength.value = value;
		if(!this._strength.changed) {
			this._strength.changed = true;
			this._changed ~= &this.encodeStrength;
		}
		return value;
	}

	public pure nothrow @safe encodeStrength(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(75));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._strength.value));
		}
	}

	public pure nothrow @property @safe @nogc int maxStrength() {
		return _maxStrength.value;
	}

	public pure nothrow @property @safe int maxStrength(int value) {
		this._cached = false;
		this._maxStrength.value = value;
		if(!this._maxStrength.changed) {
			this._maxStrength.changed = true;
			this._changed ~= &this.encodeMaxStrength;
		}
		return value;
	}

	public pure nothrow @safe encodeMaxStrength(Buffer buffer) {
		with(buffer) {
			writeBytes(varuint.encode(76));
			writeBytes(varuint.encode(2));
			writeBytes(varint.encode(this._maxStrength.value));
		}
	}

	public pure nothrow @safe encode(Buffer buffer) {
		with(buffer) {
			if(this._cached) {
				buffer.writeBytes(this._cache);
			} else {
				immutable start = buffer._buffer.length;
				writeBytes(varuint.encode(cast(uint)this._changed.length));
				foreach(del ; this._changed) del(buffer);
				this._cached = true;
				this._cache = buffer._buffer[start..$];
			}
		}
	}

	public static pure nothrow @safe Metadata decode(Buffer buffer) {
		return null;
	}

}